# -------- Generated by configure -----------

# Ensure that locale settings do not interfere with shell commands.
export LC_ALL = C

CONFIGURATION = --prefix=/home/kulina/BUILD/kgmplayer --disable-gui --enable-runtime-cpudetection --disable-relocatable --disable-gif --disable-speex --disable-gl --enable-alsa --enable-pulse --enable-vm --enable-gnutls --disable-mencoder --enable-mp3lame --enable-freetype --enable-fontconfig --disable-tv-v4l1 --enable-xv --cc=gcc

CHARSET = UTF-8
DOC_LANGS = en
DOC_LANG_ALL = cs de en es fr hu it pl ru zh_CN
MAN_LANGS = en
MAN_LANG_ALL = cs de en es fr hu it pl ru zh_CN

CATALOG = /etc/sgml/catalog
XMLLINT_COMMAND = xmllint --noout --noent --postvalid --catalogs
XSLT_COMMAND = 

prefix  = $(DESTDIR)/home/kulina/BUILD/kgmplayer
BINDIR  = $(DESTDIR)/home/kulina/BUILD/kgmplayer/bin
DATADIR = $(DESTDIR)/home/kulina/BUILD/kgmplayer/share/mplayer
LIBDIR  = $(DESTDIR)/home/kulina/BUILD/kgmplayer/lib
MANDIR  = $(DESTDIR)/home/kulina/BUILD/kgmplayer/share/man
CONFDIR = $(DESTDIR)/home/kulina/BUILD/kgmplayer/etc/mplayer

AR      = ar
ARFLAGS = rc
AR_O    = $@
AS      = gcc
CC      = gcc
CXX     = gcc
HOST_CC = gcc
INSTALL = install
INSTALLSTRIP = -s
WINDRES = windres

CFLAGS   = -Wundef  -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -fPIC  -I/home/kulina/BUILD/kgmplayer/include -I/home/kulina/BUILD/kgmplayer/include/freetype2 -I/home/kulina/BUILD/kgmplayer/include/ncursesw  -Wno-incompatible-pointer-types -Wno-implicit-function-declaration -Wno-int-conversion -fno-tree-vectorize -fno-asynchronous-unwind-tables -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE  -DPIC -D_REENTRANT -I/home/kulina/BUILD/kgmplayer/include   -I/home/kulina/BUILD/kgmplayer/include -D_REENTRANT  -I/home/kulina/BUILD/kgmplayer/include  -I/include/freetype2 -I/include -DZLIB_CONST -I/home/kulina/BUILD/kgmplayer/include/opus 
CXXFLAGS = -Wundef   -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -fPIC  -I/home/kulina/BUILD/kgmplayer/include -I/home/kulina/BUILD/kgmplayer/include/freetype2 -I/home/kulina/BUILD/kgmplayer/include/ncursesw  -Wno-incompatible-pointer-types -Wno-implicit-function-declaration -Wno-int-conversion -fno-tree-vectorize -fno-asynchronous-unwind-tables -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -DPIC -D_REENTRANT -I/home/kulina/BUILD/kgmplayer/include   -I/home/kulina/BUILD/kgmplayer/include -D_REENTRANT  -I/home/kulina/BUILD/kgmplayer/include  -I/include/freetype2 -I/include -DZLIB_CONST -I/home/kulina/BUILD/kgmplayer/include/opus  
CC_DEPFLAGS = -MMD -MP

CFLAGS_DHAHELPER         = 
CFLAGS_NO_OMIT_LEAF_FRAME_POINTER = -mno-omit-leaf-frame-pointer
CFLAGS_STACKREALIGN      = 
CFLAGS_SVGALIB_HELPER    = 

EXTRALIBS          =  -Wl,--version-script,binary.ver -Wl,-z,noexecstack  -L/home/kulina/BUILD/kgmplayer/lib    -lncurses -lrt -L/home/kulina/BUILD/kgmplayer/lib -lgnutls  -lpng -lz -ljpeg -lasound   -L/home/kulina/BUILD/kgmplayer/lib -ldvdread  -L/lib -lfreetype -lz -lbz2  -lz -lbz2 -lmad -lvorbisenc -lvorbis -logg -L/home/kulina/BUILD/kgmplayer/lib -lopus    -rdynamic -lm  
EXTRALIBS_MPLAYER  =  -lXv -lXxf86vm
EXTRALIBS_MENCODER =  -lmp3lame

MP_MSG_LIBS =  -lncurses 

GETCH = getch2.c
HELP_FILE = help/help_mp-en.h
TIMER = timer-linux.c

EXESUF      = 
EXESUFS_ALL = .exe

ARCH = x86
ARCH_X86 = yes
ARCH_IA64 = no
ARCH_SPARC = no
ARCH_ARM = no
ARCH_AVR32 = no
ARCH_SH4 = no
ARCH_PPC = no
ARCH_ALPHA = no
ARCH_MIPS = no
ARCH_PA_RISC = no
ARCH_S390 = no
ARCH_S390X = no
ARCH_VAX = no
ARCH_BFIN = no
ARCH_XTENSA = no
ARCH_TOMI = no
ARCH_GENERIC = no
ARCH_AARCH64 = no
ARCH_X86_32 = no
ARCH_X86_64 = yes
ARCH_PPC64 = no
HAVE_ALTIVEC = no
HAVE_XOP = yes
HAVE_AVX = yes
HAVE_AVX2 = yes
HAVE_FMA3 = yes
HAVE_FMA4 = yes
HAVE_MMX = yes
HAVE_MMX2 = yes
HAVE_MMXEXT = yes
HAVE_AMD3DNOW = yes
HAVE_AMD3DNOWEXT = yes
HAVE_SSE = yes
HAVE_SSE2 = yes
HAVE_SSE3 = yes
HAVE_SSSE3 = yes
HAVE_SSE4 = yes
HAVE_SSE42 = yes
HAVE_FAST_CMOV = yes
HAVE_I686 = yes
HAVE_FAST_CLZ = yes
HAVE_ARMV5TE = no
HAVE_ARMV6 = no
HAVE_ARMV6T2 = no
HAVE_VFP = no
HAVE_VFPV3 = no
HAVE_SETEND = no
HAVE_NEON = no
HAVE_IWMMXT = no
HAVE_MMI = no
HAVE_VIS = no
HAVE_MVI = no

MENCODER = no
MPLAYER  = yes

# operating system features which have local fallbacks
GETTIMEOFDAY = yes
GLOB         = yes
GLOB_WIN     = yes
MMAP         = 
SETENV       = yes
SHMEM        = no
STRSEP       = yes
VSSCANF      = yes

# features
3DFX = no
AA = no
ALSA = yes
APPLE_IR = yes
APPLE_REMOTE = auto
ARTS = no
AUDIO_INPUT = yes
BITMAP_FONT = yes
BL = no
CACA = no
CDDA = 
CDDB = no
COREAUDIO = auto
COREVIDEO = auto
DART = auto
DGA = no
DIRECT3D = auto
DIRECTFB = no
DIRECTX = auto
DVBIN = yes
DVDNAV = no
DVDREAD = yes
DXR2 = no
DXR3 = no
ESD = no
FAAC=auto
FAAD = no
FASTMEMCPY = yes
FBDEV = yes
FREETYPE = yes
FTP = yes
GIF = no
GGI = no
GL = no
GL_WIN32 = 
GL_X11 = 
GL_EGL_X11 = 
GL_SDL = 
GL_OSX = 
MATRIXVIEW = no
GUI = no
GUI_GTK = 
GUI_WIN32 = 
HAVE_POSIX_SELECT = yes
HAVE_SYS_MMAN_H = yes
HAVE_WINDOWS_H = no
IVTV = no
JACK = no
JOYSTICK = no
JPEG = yes
KAI = auto
KVA = auto
LADSPA = no
LIBA52 = no
LIBASS = yes
LIBASS_INTERNAL = yes
LIBBLURAY = no
LIBBS2B = no
LIBDCA = no
LIBDV = no
LIBLZO = no
LIBMAD = yes
LIBMENU = no
LIBMENU_DVBIN = no
LIBMPEG2 = no
LIBMPEG2_INTERNAL = no
LIBNEMESI = no
LIBNUT = no
LIBSMBCLIENT = no
LIBTHEORA = no
LIRC = no
LIVE555 = no
MACOSX_FINDER = no
MD5SUM = yes
MGA = no
MNG = no
MP3LAME = yes
MPG123 = no
MUSEPACK = no
NAS = no
NATIVE_RTSP = yes
NETWORKING = yes
OPENAL = no
OSS = yes
PE_EXECUTABLE = 
PNG = yes
PNM = yes
POSTPROC = yes
PRIORITY = no
PULSE = yes
PVR = yes
QTX_CODECS = auto
QTX_CODECS_WIN32 = 
QTX_EMULATION = no
QUARTZ = auto
RADIO=no
RADIO_CAPTURE=no
REAL_CODECS = yes
S3FB = no
SDL = no
SDL_IMAGE = no
SPEEX = no
STREAM_CACHE = yes
SGIAUDIO = auto
SNDIO = no
SUNAUDIO = no
SVGA = no
TDFXFB = no
TDFXVID = no
TGA = yes
TOOLAME=no
TV = yes
TV_BSDBT848 = auto
TV_DSHOW = no
TV_V4L  = yes
TV_V4L1 = no
TV_V4L2 = yes
TWOLAME=no
UNRAR_EXEC = yes
V4L2 = yes
VCD = yes
VDA = no
VDPAU = no
VESA = no
VIDIX = yes
VIDIX_PCIDB = 1
VIDIX_CYBERBLADE=yes
VIDIX_IVTV=no
VIDIX_MACH64=yes
VIDIX_MGA=yes
VIDIX_MGA_CRTC2=yes
VIDIX_NVIDIA=yes
VIDIX_PM2=yes
VIDIX_PM3=yes
VIDIX_RADEON=yes
VIDIX_RAGE128=yes
VIDIX_S3=yes
VIDIX_SH_VEU=no
VIDIX_SIS=yes
VIDIX_UNICHROME=yes
VORBIS = yes
VSTREAM = no
WII = no
WIN32DLL = no
WIN32WAVEOUT = auto
WIN32_EMULATION = no
WINVIDIX = 
X11 = yes
X264 = auto
XANIM_CODECS = yes
XMGA = no
XMMS_PLUGINS = no
XV = yes
XVID4 = no
XVIDIX = yes
XVMC = no
XVR100 = no
YUV4MPEG = yes
ZR = no

# FFmpeg
FFMPEG     = yes
FFMPEG_A   = yes

CONFIG_AVCODEC  = yes
CONFIG_AVDEVICE = yes
CONFIG_AVFILTER = yes
CONFIG_AVFORMAT = yes
CONFIG_AVUTIL   = yes
CONFIG_POSTPROC = yes
CONFIG_SWSCALE  = yes
CONFIG_SWRESAMPLE = yes

ASFLAGS    = $(CFLAGS)
AS_DEPFLAGS= -MMD -MP
HOSTCC     = $(HOST_CC)
HOSTCFLAGS = -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -O3
HOSTLIBS   = -lm
AS_O       = -o $@
CC_O       = -o $@
CXX_O      = -o $@
AS_C       = -c
CC_C       = -c
CXX_C      = -c
LD         = gcc
RANLIB     = true
YASM       = yasm
DEPYASM    = yasm
YASMFLAGS  = -f elf  -DPIC -m amd64
STRIP      = strip

CONFIG_FFPROBE       = no
CONFIG_LAVFI_INDEV   = no
CONFIG_AMOVIE_FILTER = no
CONFIG_MOVIE_FILTER  = no
CONFIG_SCALE_FILTER  = no
CONFIG_SELECT_FILTER = no

CONFIG_STATIC = yes
SRC_PATH      = .
DST_PATH      = /home/kulina/BUILD/kgmplayer/mplayer/ffmpeg
LIBPREF       = lib
LIBSUF        = .a
FULLNAME      = $(NAME)$(BUILDSUF)
LIBNAME       = $(LIBPREF)$(FULLNAME)$(LIBSUF)

# These are not necessary for building, since we do not use shared libraries,
# but without them target names clash, causing Make warnings by the boatload.
SLIBNAME            = $(SLIBPREF)$(FULLNAME)$(SLIBSUF)
SLIBNAME_WITH_MAJOR = $(SLIBNAME)-42

# Some FFmpeg codecs depend on these. Enable them unconditionally for now.
CONFIG_AANDCTTABLES  = yes
CONFIG_AUDIODSP = yes
CONFIG_AUDIO_FRAME_QUEUE = yes
CONFIG_BLOCKDSP= yes
CONFIG_BSWAPDSP= yes
CONFIG_CABAC   = yes
CONFIG_CHROMAPRINT = no
CONFIG_DCT     = yes
CONFIG_DWT     = yes
CONFIG_ERROR_RESILIENCE = yes
CONFIG_EXIF    = yes
CONFIG_FAANDCT = yes
CONFIG_FAANIDCT= yes
CONFIG_FDCTDSP = yes
CONFIG_FLACDSP = yes
CONFIG_FMTCONVERT = yes
CONFIG_FRAME_THREAD_ENCODER = yes
CONFIG_FFT     = yes
CONFIG_G722DSP = yes
CONFIG_GOLOMB  = yes
CONFIG_H263DSP = yes
CONFIG_H264CHROMA = yes
CONFIG_H264DSP = yes
CONFIG_H264PRED= yes
CONFIG_H264QPEL= yes
CONFIG_HPELDSP = yes
CONFIG_IIRFILTER = yes
CONFIG_IVIDSP = yes
CONFIG_JPEGTABLES = yes
CONFIG_QPELDSP = yes
CONFIG_QSV     = no
CONFIG_HUFFYUVDSP = yes
CONFIG_HUFFYUVENCDSP = yes
CONFIG_IDCTDSP = yes
CONFIG_TPELDSP = yes
CONFIG_HUFFMAN = yes
CONFIG_IMDCT15 = yes
CONFIG_INTRAX8 = yes
CONFIG_LLAUDDSP= yes
CONFIG_LLVIDDSP= yes
CONFIG_LPC     = yes
CONFIG_LSP     = yes
CONFIG_LZF = yes
CONFIG_LZO     = yes
CONFIG_MDCT    = yes
CONFIG_ME_CMP  = yes
CONFIG_MPEG_ER = yes
CONFIG_MPEGAUDIODSP = yes
CONFIG_MPEGVIDEO    = yes
CONFIG_MPEGVIDEOENC = yes
CONFIG_MSS34DSP = yes
CONFIG_PIXBLOCKDSP  = yes
CONFIG_RANGECODER   = yes
CONFIG_RDFT    = yes
CONFIG_RIFFDEC = yes
CONFIG_RIFFENC = yes
CONFIG_RTPENC_CHAIN = yes
CONFIG_RV34DSP = yes
CONFIG_SINEWIN = yes
CONFIG_SNAPPY = yes
CONFIG_STARTCODE = yes
CONFIG_TEXTUREDSP = yes
CONFIG_VIDEODSP = yes
CONFIG_VP3DSP  = yes
CONFIG_VP56DSP = yes
CONFIG_VP8DSP = yes
CONFIG_WMA_FREQS = yes
CONFIG_WMV2DSP = yes


CONFIG_MPEGAUDIO_HP = yes
!CONFIG_LIBRTMP = yes
CONFIG_LIBRTMP  = no

CONFIG_AC3DSP   = yes
CONFIG_BZLIB    = yes
CONFIG_CRYSTALHD= no
CONFIG_ENCODERS = yes
CONFIG_GNUTLS   = yes
CONFIG_GPL      = yes
CONFIG_ICONV    = yes
CONFIG_MLIB     = no
CONFIG_MPEGAUDIO=yes
CONFIG_MUXERS   = yes
CONFIG_NETWORK  = yes
CONFIG_RTPDEC   = yes
CONFIG_VF_LAVFI = no
CONFIG_VDA      = no
CONFIG_VDPAU    = no
CONFIG_XVMC     = no
CONFIG_ZLIB     = yes

HAVE_GNU_AS     = 
HAVE_OS2THREADS = auto
HAVE_PTHREADS   = yes
HAVE_SHM        = yes
HAVE_W32THREADS = auto
HAVE_THREADS    = yes
HAVE_YASM       = yes
INTRINSICS      = none

CONFIG_LIBXVID = no









X11_CFLAGS=-I/home/kulina/BUILD/kgmplayer/include 
X11_LIBS=-lX11 
