/*----------------------------------------------------------------------------
** This file has been automatically generated by configure any changes in it
** will be lost when you run configure again.
** Instead of modifying definitions here, use the --enable/--disable options
** of the configure script! See ./configure --help for details.
*---------------------------------------------------------------------------*/

#ifndef MPLAYER_CONFIG_H
#define MPLAYER_CONFIG_H

/* Undefine this if you do not want to select mono audio (left or right)
   with a stereo MPEG layer 2/3 audio stream. The command line option
   -stereo has three possible values (0 for stereo, 1 for left-only, 2 for
   right-only), with 0 being the default.
   */
#define CONFIG_FAKE_MONO 1

/* set up max. outburst. use 131072 for TrueHD SPDIF pass-through */
#define MAX_OUTBURST 131072

/* set up audio OUTBURST. Do not change this! */
#define OUTBURST 512

/* Enable fast OSD/SUB renderer (looks ugly, but uses less CPU power) */
#undef FAST_OSD
#undef FAST_OSD_TABLE

/* Required for libdvdcss and some files below stream/. */
#ifndef O_BINARY
#define O_BINARY 0
#endif

/* Define this to enable MPEG-1/2 image postprocessing in libmpeg2 */
#define MPEG12_POSTPROC 1
#define ATTRIBUTE_ALIGNED_MAX 16



#define CONFIGURATION "--prefix=/home/kulina/BUILD/kgmplayer --disable-gui --enable-runtime-cpudetection --disable-relocatable --disable-gif --disable-speex --disable-gl --enable-alsa --enable-pulse --enable-vm --enable-gnutls --disable-mencoder --enable-mp3lame --enable-freetype --enable-fontconfig --disable-tv-v4l1 --enable-xv --cc=gcc"

#define MPLAYER_DATADIR "/home/kulina/BUILD/kgmplayer/share/mplayer"
#define MPLAYER_CONFDIR "/home/kulina/BUILD/kgmplayer/etc/mplayer"
#define MPLAYER_LIBDIR "/home/kulina/BUILD/kgmplayer/lib"

/* definitions needed by included libraries */
/* libmpeg2 */

/* libdvdcss */
#define HAVE_ERRNO_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_UNISTD_H 1














/* libdvdcss + libdvdread */
#define HAVE_LIMITS_H 1
/* libdvdread */
#define HAVE_DLFCN_H 1
#define HAVE_DLFCN_H 0
#define HAVE_MEMCPY 1
#define STDC_HEADERS 1
/* libdvdnav */
#define READ_CACHE_TRACE 0


/* system headers */
#define HAVE_ALLOCA_H 1
#define HAVE_ALTIVEC_H 0
#define HAVE_MALLOC_H 1
#define HAVE_SYS_MMAN_H 1

#undef HAVE_SOUNDCARD_H
#define HAVE_SYS_SOUNDCARD_H 1
#define HAVE_SYS_SYSINFO_H 1

#define HAVE_TERMIOS_H 1
#undef HAVE_SYS_TERMIOS_H
#define HAVE_WINSOCK2_H 0
#define HAVE_CDIO_PARANOIA_H 0
#define HAVE_CDIO_PARANOIA_PARANOIA_H 0


/* system functions */
#define HAVE_GETHOSTBYNAME2 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_GLOB 1
#define HAVE_GMTIME_R 1
#define HAVE_LANGINFO 1
#define HAVE_LOCALTIME_R 1

#define HAVE_MEMALIGN 1
#define HAVE_NANOSLEEP 1
#define HAVE_POSIX_SELECT 1
#define HAVE_AUDIO_SELECT 1
#define HAVE_SETENV 1
#define HAVE_SETMODE 0
#define HAVE_SHM 1
#define HAVE_STRSEP 1


#define HAVE_TERMCAP 1
#define HAVE_TERMIOS 1
#define HAVE_VSSCANF 1


/* system-specific features */
#define ASMALIGN(ZEROBITS) ".align 1<<" #ZEROBITS "\n\t"
#define HAVE_BUILTIN_EXPECT 1
#undef HAVE_LIBDL
#define HAVE_DOS_PATHS 0
#define EXTERN_ASM 
#define EXTERN_PREFIX ""
#define CONFIG_ICONV 1
#undef HAVE_LIBKSTAT



#define CONFIG_MEMALIGN_HACK 0
#define CONFIG_PATH_MAX_CHECK 0
#undef CONFIG_PRIORITY


#define HAVE_RTC 1
#define CONFIG_UNRAR_EXEC 1


/* configurable options */
#define MSG_CHARSET "UTF-8"
#undef CONFIG_CRASH_DEBUG
#undef MP_DEBUG
#undef CONFIG_DYNAMIC_PLUGINS
#define CONFIG_FASTMEMCPY 1
#undef CONFIG_MENU
#define CONFIG_RUNTIME_CPUDETECT 1
#define CONFIG_SIGHANDLER 1
#define CONFIG_SORTSUB 1
#define CONFIG_STREAM_CACHE 1
#undef PTHREAD_CACHE


/* CPU stuff */
#define __CPU__ x86_64

#define HAVE_BIGENDIAN 0
#define HAVE_EBX_AVAILABLE 1

#define ARCH_X86 1
#define ARCH_IA64 0
#define ARCH_SPARC 0
#define ARCH_ARM 0
#define ARCH_AVR32 0
#define ARCH_SH4 0
#define ARCH_PPC 0
#define ARCH_ALPHA 0
#define ARCH_MIPS 0
#define ARCH_PA_RISC 0
#define ARCH_S390 0
#define ARCH_S390X 0
#define ARCH_VAX 0
#define ARCH_BFIN 0
#define ARCH_XTENSA 0
#define ARCH_TOMI 0
#define ARCH_GENERIC 0
#define ARCH_AARCH64 0
#define ARCH_X86_32 0
#define ARCH_X86_64 1
#define ARCH_PPC64 0
#define HAVE_ALTIVEC 0
#define HAVE_XOP 1
#define HAVE_AVX 1
#define HAVE_AVX2 1
#define HAVE_FMA3 1
#define HAVE_FMA4 1
#define HAVE_MMX 1
#define HAVE_MMX2 1
#define HAVE_MMXEXT 1
#define HAVE_AMD3DNOW 1
#define HAVE_AMD3DNOWEXT 1
#define HAVE_SSE 1
#define HAVE_SSE2 1
#define HAVE_SSE3 1
#define HAVE_SSSE3 1
#define HAVE_SSE4 1
#define HAVE_SSE42 1
#define HAVE_FAST_CMOV 1
#define HAVE_I686 1
#define HAVE_FAST_CLZ 1
#define HAVE_ARMV5TE 0
#define HAVE_ARMV6 0
#define HAVE_ARMV6T2 0
#define HAVE_VFP 0
#define HAVE_VFPV3 0
#define HAVE_SETEND 0
#define HAVE_NEON 0
#define HAVE_IWMMXT 0
#define HAVE_MMI 0
#define HAVE_VIS 0
#define HAVE_MVI 0
#define HAVE_ALTIVEC_EXTERNAL 0
#define HAVE_XOP_EXTERNAL 1
#define HAVE_AVX_EXTERNAL 1
#define HAVE_AVX2_EXTERNAL 1
#define HAVE_FMA3_EXTERNAL 1
#define HAVE_FMA4_EXTERNAL 1
#define HAVE_MMX_EXTERNAL 1
#define HAVE_MMX2_EXTERNAL 1
#define HAVE_MMXEXT_EXTERNAL 1
#define HAVE_AMD3DNOW_EXTERNAL 1
#define HAVE_AMD3DNOWEXT_EXTERNAL 1
#define HAVE_SSE_EXTERNAL 1
#define HAVE_SSE2_EXTERNAL 1
#define HAVE_SSE3_EXTERNAL 1
#define HAVE_SSSE3_EXTERNAL 1
#define HAVE_SSE4_EXTERNAL 1
#define HAVE_SSE42_EXTERNAL 1
#define HAVE_FAST_CMOV_EXTERNAL 1
#define HAVE_I686_EXTERNAL 1
#define HAVE_FAST_CLZ_EXTERNAL 1
#define HAVE_ARMV5TE_EXTERNAL 0
#define HAVE_ARMV6_EXTERNAL 0
#define HAVE_ARMV6T2_EXTERNAL 0
#define HAVE_VFP_EXTERNAL 0
#define HAVE_VFPV3_EXTERNAL 0
#define HAVE_SETEND_EXTERNAL 0
#define HAVE_NEON_EXTERNAL 0
#define HAVE_IWMMXT_EXTERNAL 0
#define HAVE_MMI_EXTERNAL 0
#define HAVE_VIS_EXTERNAL 0
#define HAVE_MVI_EXTERNAL 0
#define HAVE_ALTIVEC_INLINE 0
#define HAVE_XOP_INLINE 1
#define HAVE_AVX_INLINE 1
#define HAVE_AVX2_INLINE 1
#define HAVE_FMA3_INLINE 1
#define HAVE_FMA4_INLINE 1
#define HAVE_MMX_INLINE 1
#define HAVE_MMX2_INLINE 1
#define HAVE_MMXEXT_INLINE 1
#define HAVE_AMD3DNOW_INLINE 1
#define HAVE_AMD3DNOWEXT_INLINE 1
#define HAVE_SSE_INLINE 1
#define HAVE_SSE2_INLINE 1
#define HAVE_SSE3_INLINE 1
#define HAVE_SSSE3_INLINE 1
#define HAVE_SSE4_INLINE 1
#define HAVE_SSE42_INLINE 1
#define HAVE_FAST_CMOV_INLINE 1
#define HAVE_I686_INLINE 1
#define HAVE_FAST_CLZ_INLINE 1
#define HAVE_ARMV5TE_INLINE 0
#define HAVE_ARMV6_INLINE 0
#define HAVE_ARMV6T2_INLINE 0
#define HAVE_VFP_INLINE 0
#define HAVE_VFPV3_INLINE 0
#define HAVE_SETEND_INLINE 0
#define HAVE_NEON_INLINE 0
#define HAVE_IWMMXT_INLINE 0
#define HAVE_MMI_INLINE 0
#define HAVE_VIS_INLINE 0
#define HAVE_MVI_INLINE 0


/* Blu-ray/DVD/VCD/CD */
#define DEFAULT_CDROM_DEVICE "/dev/cdrom"
#define DEFAULT_DVD_DEVICE   "/dev/dvd"
#undef CONFIG_LIBBLURAY
#undef CONFIG_CDDB
#undef CONFIG_CDDA
#undef CONFIG_DVDNAV
#define CONFIG_DVDREAD 1
#undef CONFIG_LIBCDIO
#define CONFIG_VCD 1


/* codec libraries */
#undef CONFIG_FAAC
#undef CONFIG_FAAD
#undef CONFIG_LIBA52
#undef CONFIG_LIBDCA
#undef CONFIG_LIBDV095
#undef CONFIG_LIBLZO
#undef CONFIG_LIBMPEG2
#undef CONFIG_LIBMPEG2_INTERNAL
#define CONFIG_ILBC 0
#define CONFIG_LIBOPUS 1
#define CONFIG_LIBMAD 1
#define CONFIG_MP3LAME 1
#define CONFIG_MP3LAME_PRESET 1
#define CONFIG_MP3LAME_PRESET_MEDIUM 1
#undef CONFIG_MPG123
#undef CONFIG_MUSEPACK
#undef CONFIG_SPEEX
#undef CONFIG_OGGTHEORA
#undef CONFIG_TOOLAME

#undef CONFIG_TWOLAME
#define CONFIG_OGGVORBIS 1
#undef CONFIG_X264
#undef CONFIG_XVID4
#define CONFIG_ZLIB 1

#undef CONFIG_LIBNUT


/* binary codecs */
#undef CONFIG_QTX_CODECS
#undef CONFIG_QTX_CODECS_WIN32
#define CONFIG_REALCODECS 1
#undef WIN32_LOADER
#undef CONFIG_WIN32DLL
#define CONFIG_XANIM 1
#undef CONFIG_XMMS
#define BINARY_CODECS_PATH "/home/kulina/BUILD/kgmplayer/lib/codecs"
#define XMMS_INPUT_PLUGIN_DIR ""


/* GUI */
#undef CONFIG_GUI



/* Audio output drivers */
#define CONFIG_ALSA 1



#undef CONFIG_ESD
#undef CONFIG_ESD_LATENCY


#undef CONFIG_NAS


#define CONFIG_OSS_AUDIO 1
#define PATH_DEV_DSP "/dev/dsp"
#define PATH_DEV_MIXER "/dev/mixer"
#define CONFIG_PULSE 1

#undef CONFIG_SNDIO_AUDIO
#undef CONFIG_SUN_AUDIO


#undef CONFIG_LADSPA
#undef CONFIG_LIBBS2B


/* input */
#define CONFIG_APPLE_IR 1



#undef CONFIG_JOYSTICK
#undef CONFIG_LIRC
#undef CONFIG_LIRCC
#define CONFIG_PVR 1
#undef CONFIG_RADIO
#undef CONFIG_RADIO_BSDBT848
#undef CONFIG_RADIO_CAPTURE
#undef CONFIG_RADIO_V4L
#undef CONFIG_RADIO_V4L2
#define CONFIG_TV 1

#undef CONFIG_TV_DSHOW
#define CONFIG_TV_V4L 1

#define CONFIG_TV_V4L2 1


/* font stuff */
#define CONFIG_ASS 1
#define CONFIG_ASS_INTERNAL 1
#define CONFIG_BITMAP_FONT 1
#undef CONFIG_ENCA
#define CONFIG_FONTCONFIG 1
#define CONFIG_FREETYPE 1
#define CONFIG_FRIBIDI 1


/* networking */
#define HAVE_CLOSESOCKET 0
#define CONFIG_FTP 1
#define HAVE_AF_INET6 1
#define HAVE_INET_ATON 1
#define HAVE_INET_PTON 1
#undef CONFIG_LIVE555
#undef CONFIG_LIBNEMESI
#define CONFIG_NETWORKING 1
#undef CONFIG_LIBSMBCLIENT
#undef CONFIG_VSTREAM


/* libvo options */
#undef CONFIG_3DFX
#undef CONFIG_AA
#undef CONFIG_BL
#undef CONFIG_CACA

#undef CONFIG_DGA
#undef CONFIG_DGA1
#undef CONFIG_DGA2

#undef CONFIG_DIRECTFB

#define CONFIG_DVB 1
#define CONFIG_DVBIN 1
#undef CONFIG_DXR2
#undef CONFIG_DXR3
#define CONFIG_FBDEV 1
#undef CONFIG_GGI
#undef CONFIG_GGIWMH
#undef CONFIG_GIF
#undef CONFIG_GIF_4

#undef CONFIG_GL
#undef CONFIG_GL_WIN32
#undef CONFIG_GL_X11
#undef CONFIG_GL_EGL_ANDROID
#undef CONFIG_GL_EGL_X11
#undef CONFIG_GL_SDL
#undef CONFIG_GL_OSX
#undef CONFIG_MATRIXVIEW
#undef CONFIG_IVTV
#define CONFIG_JPEG 1

#define CONFIG_MD5SUM 1
#undef CONFIG_MGA
#define CONFIG_MLIB 0
#undef CONFIG_MNG
#define CONFIG_POSTPROC 1
#define CONFIG_PNG 1
#define CONFIG_PNM 1

#undef CONFIG_S3FB
#undef CONFIG_SDL
#undef CONFIG_SDL_SDL_H
#undef CONFIG_SVGALIB
#undef CONFIG_TDFXFB
#undef CONFIG_XVR100
#define CONFIG_TGA 1
#define CONFIG_V4L2_DECODER 1
#define CONFIG_VDPAU 0
#undef CONFIG_VESA
#define CONFIG_VIDIX 1
#define CONFIG_VIDIX_DRV_CYBERBLADE 1
#undef CONFIG_VIDIX_DRV_IVTV
#define CONFIG_VIDIX_DRV_MACH64 1
#define CONFIG_VIDIX_DRV_MGA 1
#define CONFIG_VIDIX_DRV_MGA_CRTC2 1
#define CONFIG_VIDIX_DRV_NVIDIA 1
#define CONFIG_VIDIX_DRV_PM3 1
#define CONFIG_VIDIX_DRV_RADEON 1
#define CONFIG_VIDIX_DRV_RAGE128 1
#define CONFIG_VIDIX_DRV_S3 1
#undef CONFIG_VIDIX_DRV_SH_VEU
#define CONFIG_VIDIX_DRV_SIS 1
#define CONFIG_VIDIX_DRV_UNICHROME 1

#define CONFIG_XF86VM 1
#undef CONFIG_WII
#define CONFIG_X11 1
#undef CONFIG_XDPMS
#define CONFIG_XF86XK 1
#undef CONFIG_XINERAMA
#undef CONFIG_XMGA
#undef CONFIG_XSS
#define CONFIG_XV 1
#define CONFIG_XVMC 0

#define CONFIG_YUV4MPEG 1
#undef CONFIG_ZR


/* FFmpeg */
#define av_restrict restrict

#define CONFIG_FFMPEG 1
#define CONFIG_FFMPEG_A 1


#define CONFIG_DECODERS 1
#define CONFIG_ENCODERS 1
#define CONFIG_DEMUXERS 1
#define CONFIG_MUXERS 1
#define CONFIG_RTPDEC 1

/* selectable features */
#define CONFIG_HARDCODED_TABLES 0
#define CONFIG_MPEGAUDIO_HP 1
#define CONFIG_NETWORK 1


/* headers */
#define HAVE_ARPA_INET_H 1
#define HAVE_DIRECT_H 0
#define HAVE_IO_H 0
#define HAVE_POLL_H 1
#define HAVE_WINDOWS_H 0

/* external libraries */
#define CONFIG_BZLIB 1
#define CONFIG_CRYSTALHD 0
#define CONFIG_LIBFAAC 0
#define CONFIG_LIBDIRAC 0
#define CONFIG_LIBGSM 0
#define CONFIG_LIBOPENCORE_AMRNB 0
#define LIBOPENCORE_AMRWB 0
#define CONFIG_LIBOPENJPEG 0
#define CONFIG_LIBRTMP 0
#define CONFIG_LIBSCHROEDINGER 0
#define CONFIG_LIBMP3LAME 0
#define CONFIG_LIBX264 0
#define CONFIG_LIBXVID 0

/* system features */
#define HAVE_FAST_64BIT 1
#define HAVE_FAST_UNALIGNED 1


#define HAVE_LOCAL_ALIGNED_8 1
#define HAVE_LOCAL_ALIGNED_16 1
#define HAVE_LOCAL_ALIGNED_32 1
#define HAVE_OS2THREADS 0
#define CONFIG_PIC 1
#define HAVE_PTHREADS 1
#define HAVE_PTHREAD_CANCEL 1
#define HAVE_SOCKLEN_T 1
#define HAVE_STRUCT_ADDRINFO 1
#define HAVE_STRUCT_IPV6_MREQ 1
#define HAVE_STRUCT_SOCKADDR_IN6 1
#define HAVE_STRUCT_SOCKADDR_SA_LEN 0
#define HAVE_STRUCT_SOCKADDR_STORAGE 1
#define HAVE_THREADS 1
#define HAVE_W32THREADS 0

#define HAVE_XMM_CLOBBERS 1
#define HAVE_YASM 1

/* system functions */
#define HAVE_ALIGNED_MALLOC 0
#define HAVE_BSWAP 1


#define HAVE_ATANF 1
#define HAVE_ATAN2F 1
#define HAVE_CBRT 1
#define HAVE_CBRTF 1
#define HAVE_COSF 1
#define HAVE_EXPF 1
#define HAVE_EXP2 1
#define HAVE_EXP2F 1
#define HAVE_FMINF 1
#define HAVE_GETADDRINFO 1
#define HAVE_HYPOT 1
#define HAVE_ISFINITE 1
#define HAVE_ISINF 1
#define HAVE_ISNAN 1
#define HAVE_LDEXPF 1
#define HAVE_LLRINT 1
#define HAVE_LLRINTF 1
#define HAVE_LOG2 1
#define HAVE_LOG2F 1
#define HAVE_LOG10F 1
#define HAVE_LRINT 1
#define HAVE_LRINTF 1
#define HAVE_MKSTEMP 1
#define HAVE_MMAP 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_POWF 1
#define HAVE_MPROTECT 0
#define HAVE_RINT 1
#define HAVE_ROUND 1
#define HAVE_ROUNDF 1
#define HAVE_SINF 1
#define HAVE_TRUNC 1
#define HAVE_TRUNCF 1
#define HAVE_ERF 1

#define HAVE_INCOMPATIBLE_LIBAV_ABI 0
#define HAVE_MSVCRT 0
#define HAVE_PRAGMA_DEPRECATED 0
#define CONFIG_AUDIO_FLOAT 0
#define CONFIG_AVCODEC 1
#define CONFIG_AVSERVER 0
#define CONFIG_CHROMAPRINT 0
#define CONFIG_DXVA2 0
#define CONFIG_FASTDIV 0
#define CONFIG_FFSERVER 0
#define CONFIG_FTRAPV 0
#define CONFIG_GNUTLS 1
#define CONFIG_GPL 1
#define CONFIG_GRAY 0
#define CONFIG_LIBMODPLUG 0
#define CONFIG_LIBVORBIS 0
#define CONFIG_MEMORY_POISONING 0
#define CONFIG_OPENSSL 0
#define CONFIG_POWERPC_PERF 0
/* For now prefer speed over avoiding potential invalid reads */
#define CONFIG_SAFE_BITSTREAM_READER 0
#define CONFIG_SHARED 0
#define CONFIG_SMALL 0
#define CONFIG_SWSCALE_ALPHA 1
#define SWS_MAX_FILTER_SIZE 256
#define CONFIG_QSV 0
#define CONFIG_VAAPI 0

#define HAVE_ALIGNED_STACK 1
#define HAVE_AS_DN_DIRECTIVE 1
#define HAVE_AS_FUNC 1
#define HAVE_ASM_MOD_Q 1
#define HAVE_ATOMICS_GCC 1
#define HAVE_COPYSIGN 1
#define HAVE_SYNC_VAL_COMPARE_AND_SWAP 1
#define HAVE_ATOMICS_NATIVE 1
#define HAVE_ATTRIBUTE_PACKED 1
#define HAVE_GETHRTIME 0
#define HAVE_INLINE_ASM 1
#define HAVE_INLINE_ASM_NONLOCAL_LABELS 1
#define HAVE_INLINE_ASM_DIRECT_SYMBOL_REFS 1
#define HAVE_INTRINSICS_NEON 0
#define HAVE_ISATTY 0
#define HAVE_LDBRX 0
#define HAVE_LIBC_MSVCRT 0
#define HAVE_MACH_MACH_TIME_H 0
#define HAVE_MAPVIEWOFFILE 0
#define HAVE_MIPSDSP 0
#define HAVE_MIPSDSPR1 0
#define HAVE_MIPSFPU 0
#define HAVE_MM_EMPTY 0
#define HAVE_PPC4XX 0
#define HAVE_RDTSC 0
#define HAVE_SECTION_DATA_REL_RO 0
#define HAVE_SIMD_ALIGN_16 1
#define HAVE_STRERROR_R 0
#define HAVE_STRPTIME 0
#define HAVE_STRUCT_POLLFD 0
#define HAVE_SYMVER_ASM_LABEL 0
#define HAVE_SYMVER_GNU_ASM 0
#define HAVE_SYNC_SYNCHRONIZE 1
#define HAVE_SYS_SELECT_H 0
#define HAVE_VIRTUALALLOC 0

/* Some FFmpeg codecs depend on these. Enable them unconditionally for now. */
#define CONFIG_AANDCTTABLES 1
#define CONFIG_AUDIODSP 1
#define CONFIG_AUDIO_FRAME_QUEUE 1
#define CONFIG_BLOCKDSP 1
#define CONFIG_BSWAPDSP 1
#define CONFIG_DCT 1
#define CONFIG_DVPROFILE 1
#define CONFIG_DWT 1
#define CONFIG_ERROR_RESILIENCE 1
#define CONFIG_EXIF 1
#define CONFIG_FAANDCT 1
#define CONFIG_FAANIDCT 1
#define CONFIG_FDCTDSP 1
#define CONFIG_FLACDSP 1
#define CONFIG_FMTCONVERT 1
#define CONFIG_FRAME_THREAD_ENCODER 1
#define CONFIG_FFT 1
#define CONFIG_G722DSP 1
#define CONFIG_GOLOMB 1
#define CONFIG_H263DSP 1
#define CONFIG_H264CHROMA 1
#define CONFIG_H264DSP 1
#define CONFIG_H264PRED 1
#define CONFIG_H264QPEL 1
#define CONFIG_HUFFMAN 1
#define CONFIG_IDCTDSP 1
#define CONFIG_IVIDSP 1
#define CONFIG_LPC 1
#define CONFIG_LZF 1
#define CONFIG_LZO 1
#define CONFIG_MDCT 1
#define CONFIG_ME_CMP 1
#define CONFIG_MPEG_ER 1
#define CONFIG_MPEGVIDEO 1
#define CONFIG_MSS34DSP 1
#define CONFIG_PIXBLOCKDSP 1
#define CONFIG_RDFT 1
#define CONFIG_RIFFDEC 1
#define CONFIG_RIFFENC 1
#define CONFIG_RV34DSP 1
#define CONFIG_SNAPPY 1
#define CONFIG_STARTCODE 1
#define CONFIG_TEXTUREDSP 1
#define CONFIG_VIDEODSP 1
#define CONFIG_VP56DSP 1
#define CONFIG_VP8DSP 1
#define CONFIG_WMA_FREQS 1
#define CONFIG_WMV2DSP 1

/* Use these registers in FFmpeg x86 inline asm. No proper detection yet. */
#ifndef MP_DEBUG
#define HAVE_EBP_AVAILABLE 1
#else
#define HAVE_EBP_AVAILABLE 0
#endif

#define FFMPEG_CONFIGURATION "--enable-gpl --enable-postproc"
#define FFMPEG_LICENSE "GPL version 2 or later"

#define LIBAV_CONFIGURATION FFMPEG_CONFIGURATION
#define LIBAV_LICENSE FFMPEG_LICENSE











#endif /* MPLAYER_CONFIG_H */
