int ArrangeVideoAVMlistcallback(int item,int i,void *Tmp) ;
void  ArrangeVideoAVMlistinit (DIX *X,void *pt) ;
int ArrangeVideoAVMbutnscallback(int butno,int i,void *Tmp) ;
void  ArrangeVideoAVMbutnsinit (DIN *B,void *pt) ;
int ArrangeVideoAVMrescallback(int cellno,int i,void *Tmp) ;
int ArrangeVideoAVMgocallback(int butno,int i,void *Tmp) ;
void  ArrangeVideoAVMgoinit (DIL *B,void *pt) ;
int ArrangeVideoAVMoutcallback(int cellno,int i,void *Tmp) ;
int ArrangeVideoAVMbrowsecallback(int butno,int i,void *Tmp) ;
void  ArrangeVideoAVMbrowseinit (DIN *B,void *pt) ;
int ArrangeVideoinit(void *Tmp) ;
int ArrangeVideocleanup(void *Tmp) ;
void *RunArrangeVideo(void *,void *) ;
int MakeArrangeVideoGroup(DIALOG *,void *) ;
void * ArrangeVideoAction(void *,void *) ;
int ArrangeVideoSetup(void *Tmp,void *args) ;
int ModifyArrangeVideo(void *Tmp,int GrpId) ;
int ArrangeVideoCallBack(void *Tmp,void *tmp) ;
int ArrangeVideoResizeCallBack(void *Tmp) ;
int ArrangeVideoWaitCallBack(void *Tmp) ;
