int AudioJoinVideoListcallback(int item,int i,void *Tmp) ;
void  AudioJoinVideoListinit (DIX *X,void *pt) ;
int AudioJoinAudioJoinWidget2callback(int butno,int i,void *Tmp) ;
void  AudioJoinAudioJoinWidget2init (DIN *B,void *pt) ;
int AudioJoinAjoinOutcallback(int cellno,int i,void *Tmp) ;
int AudioJoinJoinAudioscallback(int butno,int i,void *Tmp) ;
void  AudioJoinJoinAudiosinit (DIL *B,void *pt) ;
int AudioJoinAJbrowsecallback(int butno,int i,void *Tmp) ;
void  AudioJoinAJbrowseinit (DIN *B,void *pt) ;
int AudioJoininit(void *Tmp) ;
int AudioJoincleanup(void *Tmp) ;
void *RunAudioJoin(void *,void *) ;
int MakeAudioJoinGroup(DIALOG *,void *) ;
void * AudioJoinAction(void *,void *) ;
int ModifyAudioJoin(void *Tmp,int GrpId) ;
int AudioJoinCallBack(void *Tmp,void *tmp) ;
int AudioJoinResizeCallBack(void *Tmp) ;
int AudioJoinWaitCallBack(void *Tmp) ;
