int AudioSpeedATinputcallback(int cellno,int i,void *Tmp) ;
int AudioSpeedATbrowsecallback(int butno,int i,void *Tmp) ;
void  AudioSpeedATbrowseinit (DIN *B,void *pt) ;
int AudioSpeedAToutputcallback(int cellno,int i,void *Tmp) ;
int AudioSpeedATspeedcallback(int cellno,int i,void *Tmp) ;
int AudioSpeedATdocallback(int butno,int i,void *Tmp) ;
void  AudioSpeedATdoinit (DIL *B,void *pt) ;
int AudioSpeedASOutcallback(int butno,int i,void *Tmp) ;
void  AudioSpeedASOutinit (DIN *B,void *pt) ;
int AudioSpeedinit(void *Tmp) ;
int AudioSpeedcleanup(void *Tmp) ;
void *RunAudioSpeed(void *,void *) ;
int MakeAudioSpeedGroup(DIALOG *,void *) ;
void * AudioSpeedAction(void *,void *) ;
int AudioSpeedSetup(void *Tmp,void *args) ;
int ModifyAudioSpeed(void *Tmp,int GrpId) ;
int AudioSpeedCallBack(void *Tmp,void *tmp) ;
int AudioSpeedResizeCallBack(void *Tmp) ;
int AudioSpeedWaitCallBack(void *Tmp) ;
