int  AudioConverttextbox1callback(int cellno,int i,void *Tmp);
int  AudioConvertbutton1callback(int butno,int i,void *Tmp) ;
void  AudioConvertbutton1init(DIN *B,void *pt) ;
int  AudioConverttextbox2callback(int cellno,int i,void *Tmp);
int  AudioConvertbrowser1callback(int item,int i,void *Tmp) ;
void  AudioConvertbrowser1init(DIRA *R,void *pt) ;
int  AudioConvertbrowser2callback(int item,int i,void *Tmp) ;
void  AudioConvertbrowser2init(DIRA *R,void *pt) ;
int  AudioConvertsplbutton1callback(int butno,int i,void *Tmp) ;
void  AudioConvertsplbutton1init(DIL *B,void *pt) ;
int AudioConvertinit(void *Tmp) ;
int AudioConvertcleanup(void *Tmp) ;
int AudioConvertCallBack(void *Tmp,void *tmp) ;
int AudioConvertResizeCallBack(void *Tmp) ;
int AudioConvertWaitCallBack(void *Tmp) ;
