int BoverlayOBinputcallback(int cellno,int i,void *Tmp) ;
int BoverlayOBinputbrowsecallback(int butno,int i,void *Tmp) ;
void  BoverlayOBinputbrowseinit (DIN *B,void *pt) ;
int BoverlayOBgocallback(int butno,int i,void *Tmp) ;
void  BoverlayOBgoinit (DIL *B,void *pt) ;
int BoverlayOBoutcallback(int cellno,int i,void *Tmp) ;
int BoverlayOBOutbrowsecallback(int butno,int i,void *Tmp) ;
void  BoverlayOBOutbrowseinit (DIN *B,void *pt) ;
int BoverlayOBRescallback(int cellno,int i,void *Tmp) ;
int BoverlayOBFpscallback(int cellno,int i,void *Tmp) ;
int BoverlayOBQtycallback(int item,int i,void *Tmp) ;
void  BoverlayOBQtyinit (DIRA *R,void *pt) ;
int BoverlayOBcolorcallback(int butno,int i,void *Tmp) ;
void  BoverlayOBcolorinit (DIN *B,void *pt) ;
int Boverlayinit(void *Tmp) ;
int Boverlaycleanup(void *Tmp) ;
void *RunBoverlay(void *,void *) ;
int MakeBoverlayGroup(DIALOG *,void *) ;
void * BoverlayAction(void *,void *) ;
int BoverlaySetup(void *Tmp,void *args) ;
int ModifyBoverlay(void *Tmp,int GrpId) ;
int BoverlayCallBack(void *Tmp,void *tmp) ;
int BoverlayResizeCallBack(void *Tmp) ;
int BoverlayWaitCallBack(void *Tmp) ;
