int  Controlssplbutton1callback(int butno,int i,void *Tmp) ;
int  AControlssplbutton1callback(int butno,int i,void *Tmp) ;
void  Controlssplbutton1init(DIL *B,void *pt) ;
int  Controlsdslide1callback(int val,int i,void *Tmp) ;
int  Controlsdslide2callback(int val,int i,void *Tmp) ;
int  AControlsdslide1callback(int val,int i,void *Tmp) ;
int  AControlsdslide2callback(int val,int i,void *Tmp) ;
int Controlsinit(void *Tmp) ;
int AControlsinit(void *Tmp) ;
int Controlscleanup(void *Tmp) ;
int ControlsCallBack(void *Tmp,void *tmp) ;
int AControlsCallBack(void *Tmp,void *tmp) ;
int AControlsCallBack(void *Tmp,void *tmp) ;
int ControlsResizeCallBack(void *Tmp) ;
int ControlsWaitCallBack(void *Tmp) ;
int AControlsWaitCallBack(void *Tmp) ;
