int  ConvertVideotextbox1callback(int cellno,int i,void *Tmp);
int  ConvertVideobutton1callback(int butno,int i,void *Tmp) ;
void  ConvertVideobutton1init(DIN *B,void *pt) ;
int  ConvertVideotextbox2callback(int cellno,int i,void *Tmp);
int  ConvertVideobrowser1callback(int item,int i,void *Tmp) ;
void  ConvertVideobrowser1init(DIRA *R,void *pt) ;
int  ConvertVideobrowser2callback(int item,int i,void *Tmp) ;
void  ConvertVideobrowser2init(DIRA *R,void *pt) ;
int  ConvertVideobrowser3callback(int item,int i,void *Tmp) ;
void  ConvertVideobrowser3init(DIRA *R,void *pt) ;
int  ConvertVideosplbutton1callback(int butno,int i,void *Tmp) ;
void  ConvertVideosplbutton1init(DIL *B,void *pt) ;
int  ConvertVideobrowser4callback(int item,int i,void *Tmp) ;
void  ConvertVideobrowser4init(DIRA *R,void *pt) ;
int ConvertVideoinit(void *Tmp) ;
int ConvertVideocleanup(void *Tmp) ;
int ConvertVideoCallBack(void *Tmp,void *tmp) ;
int ConvertVideoResizeCallBack(void *Tmp) ;
int ConvertVideoWaitCallBack(void *Tmp) ;
