int ConvertVideoVCinboxcallback(int cellno,int i,void *Tmp) ;
int ConvertVideoVCinbrcallback(int butno,int i,void *Tmp) ;
void  ConvertVideoVCinbrinit (DIN *B,void *pt) ;
int ConvertVideoVCoutboxcallback(int cellno,int i,void *Tmp) ;
int ConvertVideoVCradio1callback(int item,int i,void *Tmp) ;
void  ConvertVideoVCradio1init (DIRA *R,void *pt) ;
int ConvertVideoVCradio2callback(int item,int i,void *Tmp) ;
void  ConvertVideoVCradio2init (DIRA *R,void *pt) ;
int ConvertVideoVCradio3callback(int item,int i,void *Tmp) ;
void  ConvertVideoVCradio3init (DIRA *R,void *pt) ;
int ConvertVideoVconvertcallback(int butno,int i,void *Tmp) ;
void  ConvertVideoVconvertinit (DIL *B,void *pt) ;
int ConvertVideoVCradio4callback(int item,int i,void *Tmp) ;
void  ConvertVideoVCradio4init (DIRA *R,void *pt) ;
int ConvertVideoVCoutbrcallback(int butno,int i,void *Tmp) ;
void  ConvertVideoVCoutbrinit (DIN *B,void *pt) ;
int ConvertVideoCVaspcallback(int cellno,int i,void *Tmp) ;
int ConvertVideoCVxrescallback(int cellno,int i,void *Tmp) ;
int ConvertVideoCVrangecallback(int cellno,int i,void *Tmp) ;
int ConvertVideoinit(void *Tmp) ;
int ConvertVideocleanup(void *Tmp) ;
void *RunConvertVideo(void *,void *) ;
int MakeConvertVideoGroup(DIALOG *,void *) ;
void * ConvertVideoAction(void *,void *) ;
int ModifyConvertVideo(void *Tmp,int GrpId) ;
int ConvertVideoCallBack(void *Tmp,void *tmp) ;
int ConvertVideoResizeCallBack(void *Tmp) ;
int ConvertVideoWaitCallBack(void *Tmp) ;
