int CropCRPinput1callback(int cellno,int i,void *Tmp) ;
int CropCRPinput1browsecallback(int butno,int i,void *Tmp) ;
void  CropCRPinput1browseinit (DIN *B,void *pt) ;
int CropCRPgocallback(int butno,int i,void *Tmp) ;
void  CropCRPgoinit (DIL *B,void *pt) ;
int CropCRPoutcallback(int cellno,int i,void *Tmp) ;
int CropCRPOutbrowsecallback(int butno,int i,void *Tmp) ;
void  CropCRPOutbrowseinit (DIN *B,void *pt) ;
int CropCRPloccallback(int cellno,int i,void *Tmp) ;
int CropCRPrescallback(int cellno,int i,void *Tmp) ;
int CropCRPselectcallback(int butno,int i,void *Tmp) ;
void  CropCRPselectinit (DIN *B,void *pt) ;
int Cropinit(void *Tmp) ;
int Cropcleanup(void *Tmp) ;
void *RunCrop(void *,void *) ;
int MakeCropGroup(DIALOG *,void *) ;
void * CropAction(void *,void *) ;
int ModifyCrop(void *Tmp,int GrpId) ;
int CropCallBack(void *Tmp,void *tmp) ;
int CropResizeCallBack(void *Tmp) ;
int CropWaitCallBack(void *Tmp) ;
