int imgs2vimgs2vWidget2callback(int butno,int i,void *Tmp) ;
void  imgs2vimgs2vWidget2init (DIN *B,void *pt) ;
int imgs2vimgs2vBrowsercallback(int item,int i,void *Tmp) ;
void  imgs2vimgs2vBrowserinit (DIX *X,void *pt) ;
int imgs2vimgs2vVideocallback(int cellno,int i,void *Tmp) ;
int imgs2vOptionscallback(int cellno,int i,void *Tmp) ;
int imgs2vFitWidgetcallback(int item,int i,void *Tmp) ;
void  imgs2vFitWidgetinit (DIRA *R,void *pt) ;
int imgs2vimgs2vWidget9callback(int butno,int i,void *Tmp) ;
void  imgs2vimgs2vWidget9init (DIL *B,void *pt) ;
int imgs2vObrowsecallback(int butno,int i,void *Tmp) ;
void  imgs2vObrowseinit (DIN *B,void *pt) ;
int imgs2vinit(void *Tmp) ;
int imgs2vcleanup(void *Tmp) ;
void *Runimgs2v(void *,void *) ;
int Makeimgs2vGroup(DIALOG *,void *) ;
void * imgs2vAction(void *,void *) ;
int Modifyimgs2v(void *Tmp,int GrpId) ;
int imgs2vCallBack(void *Tmp,void *tmp) ;
int imgs2vResizeCallBack(void *Tmp) ;
int imgs2vWaitCallBack(void *Tmp) ;
