int  imgs2vbutton1callback(int butno,int i,void *Tmp) ;
void  imgs2vbutton1init(DIN *B,void *pt) ;
int  imgs2vbrowser1callback(int item,int i,void *Tmp) ;
void  imgs2vbrowser1init(DIX *X,void *pt) ;
int  imgs2vtextbox1callback(int cellno,int i,void *Tmp);
int  imgs2vtextbox2callback(int cellno,int i,void *Tmp);
int  imgs2vbrowser2callback(int item,int i,void *Tmp) ;
void  imgs2vbrowser2init(DIRA *R,void *pt) ;
int  imgs2vsplbutton1callback(int butno,int i,void *Tmp) ;
void  imgs2vsplbutton1init(DIL *B,void *pt) ;
int imgs2vinit(void *Tmp) ;
int imgs2vcleanup(void *Tmp) ;
int imgs2vCallBack(void *Tmp,void *tmp) ;
int imgs2vResizeCallBack(void *Tmp) ;
int imgs2vWaitCallBack(void *Tmp) ;
