int  kgGetFilesbutton1callback(int butno,int i,void *Tmp) ;
void  kgGetFilesbutton1init(DIN *B,void *pt) ;
int  kgGetFilessplbutton1callback(int butno,int i,void *Tmp) ;
void  kgGetFilessplbutton1init(DIL *B,void *pt) ;
int  kgGetFilesbrowser1callback(int item,int i,void *Tmp) ;
void  kgGetFilesbrowser1init(DIY *Y,void *pt) ;
int  kgGetFilesbrowser2callback(int item,int i,void *Tmp) ;
void  kgGetFilesbrowser2init(DIE *E,void *pt) ;
int  kgGetFilesbrowser3callback(int item,int i,void *Tmp) ;
void  kgGetFilesbrowser3init(DIY *Y,void *pt) ;
int  kgGetFilesbutton2callback(int butno,int i,void *Tmp) ;
void  kgGetFilesbutton2init(DIN *B,void *pt) ;
int kgGetFilesinit(void *Tmp) ;
int kgGetFilescleanup(void *Tmp) ;
int kgGetFilesCallBack(void *Tmp,void *tmp) ;
int kgGetFilesResizeCallBack(void *Tmp) ;
int kgGetFilesWaitCallBack(void *Tmp) ;
char *kgCopyString(char *str);
