int  kgMplayersplbutton1callback(int butno,int i,void *Tmp) ;
void  kgMplayersplbutton1init(DIL *B,void *pt) ;
int  kgMplayerbrowser1callback(int item,int i,void *Tmp) ;
void  kgMplayerbrowser1init(DIRA *R,void *pt) ;
int  kgMplayerbrowser2callback(int item,int i,void *Tmp) ;
int  kgMplayerbutton1callback(int butno,int i,void *Tmp) ;
void  kgMplayerbutton1init(DIN *B,void *pt) ;
int  kgMplayerdslide1callback(int val,int i,void *Tmp) ;
int  kgMplayerdslide2callback(int val,int i,void *Tmp) ;
int  kgMplayerdslide3callback(int val,int i,void *Tmp) ;
int  kgMplayerdslide4callback(int val,int i,void *Tmp) ;
int  kgMplayerbutton2callback(int butno,int i,void *Tmp) ;
void  kgMplayerbutton2init(DIN *B,void *pt) ;
int  kgMplayerbutton3callback(int butno,int i,void *Tmp) ;
void  kgMplayerbutton3init(DIN *B,void *pt) ;
int  kgMplayerbrowser3callback(int item,int i,void *Tmp) ;
void  kgMplayerbrowser3init(DICH *C,void *pt) ;
int kgMplayerinit(void *Tmp) ;
int kgMplayercleanup(void *Tmp) ;
int kgMplayerCallBack(void *Tmp,void *tmp) ;
int kgMplayerResizeCallBack(void *Tmp) ;
int kgMplayerWaitCallBack(void *Tmp) ;
void  kgMplayersplbutton3init(DIL *B,void *pt) ;
int  kgMplayerbutton3callback(int butno,int i,void *Tmp);
int  kgMplayerbutton4callback(int butno,int i,void *Tmp);
void  kgMplayerbutton4init(DIN *B,void *pt);
int  kgMplayerbrowser4callback(int item,int i,void *Tmp);
void  kgMplayerbrowser4init(DICH *C,void *pt);
int  kgMplayerbrowser5callback(int item,int i,void *Tmp) ;
void  kgMplayerbrowser5init(DICH *C,void *pt) ;
int  kgMplayerbrowser6callback(int item,int i,void *Tmp) ;
void  kgMplayerbrowser6init(DIRA *R,void *pt) ;

void *logo(int l,int w);
