int  Loudnormbrowser1callback(int item,int i,void *Tmp) ;
void  Loudnormbrowser1init(DIX *X,void *pt) ;
int  Loudnormbutton1callback(int butno,int i,void *Tmp) ;
void  Loudnormbutton1init(DIN *B,void *pt) ;
int  Loudnormsplbutton1callback(int butno,int i,void *Tmp) ;
void  Loudnormsplbutton1init(DIL *B,void *pt) ;
int  Loudnormtextbox1callback(int cellno,int i,void *Tmp);
int Loudnorminit(void *Tmp) ;
int Loudnormcleanup(void *Tmp) ;
int ModifyLoudnorm(void *Tmp,int GrpId) ;
int LoudnormCallBack(void *Tmp,void *tmp) ;
int LoudnormResizeCallBack(void *Tmp) ;
int LoudnormWaitCallBack(void *Tmp) ;
