int  MakeCutsbrowser1callback(int item,int i,void *Tmp) ;
void  MakeCutsbrowser1init(DIX *X,void *pt) ;
int  MakeCutsbutton1callback(int butno,int i,void *Tmp) ;
void  MakeCutsbutton1init(DIN *B,void *pt) ;
int  MakeCutstextbox1callback(int cellno,int i,void *Tmp);
int  MakeCutssplbutton1callback(int butno,int i,void *Tmp) ;
void  MakeCutssplbutton1init(DIL *B,void *pt) ;
int  MakeCutstextbox2callback(int cellno,int i,void *Tmp);
int  MakeCutsbutton2callback(int butno,int i,void *Tmp) ;
void  MakeCutsbutton2init(DIN *B,void *pt) ;
int MakeCutsinit(void *Tmp) ;
int MakeCutscleanup(void *Tmp) ;
int MakeCutsCallBack(void *Tmp,void *tmp) ;
int MakeCutsResizeCallBack(void *Tmp) ;
int MakeCutsWaitCallBack(void *Tmp) ;
