int  Normalisebrowser1callback(int item,int i,void *Tmp) ;
void  Normalisebrowser1init(DIX *X,void *pt) ;
int  Normalisebutton1callback(int butno,int i,void *Tmp) ;
void  Normalisebutton1init(DIN *B,void *pt) ;
int  Normalisesplbutton1callback(int butno,int i,void *Tmp) ;
void  Normalisesplbutton1init(DIL *B,void *pt) ;
int  Normalisetextbox1callback(int cellno,int i,void *Tmp);
int Normaliseinit(void *Tmp) ;
int Normalisecleanup(void *Tmp) ;
int ModifyNormalise(void *Tmp,int GrpId) ;
int NormaliseCallBack(void *Tmp,void *tmp) ;
int NormaliseResizeCallBack(void *Tmp) ;
int NormaliseWaitCallBack(void *Tmp) ;
