int OverlayOLYinput1callback(int cellno,int i,void *Tmp) ;
int OverlayOLYinput1browsecallback(int butno,int i,void *Tmp) ;
void  OverlayOLYinput1browseinit (DIN *B,void *pt) ;
int OverlayOLYinput2callback(int cellno,int i,void *Tmp) ;
int OverlayOLYinput2browsecallback(int butno,int i,void *Tmp) ;
void  OverlayOLYinput2browseinit (DIN *B,void *pt) ;
int OverlayOLYgocallback(int butno,int i,void *Tmp) ;
void  OverlayOLYgoinit (DIL *B,void *pt) ;
int OverlayOLYoutcallback(int cellno,int i,void *Tmp) ;
int OverlayOLYOutbrowsecallback(int butno,int i,void *Tmp) ;
void  OverlayOLYOutbrowseinit (DIN *B,void *pt) ;
int OverlayOLYloccallback(int cellno,int i,void *Tmp) ;
int Overlayinit(void *Tmp) ;
int Overlaycleanup(void *Tmp) ;
void *RunOverlay(void *,void *) ;
int MakeOverlayGroup(DIALOG *,void *) ;
void * OverlayAction(void *,void *) ;
int ModifyOverlay(void *Tmp,int GrpId) ;
int OverlayCallBack(void *Tmp,void *tmp) ;
int OverlayResizeCallBack(void *Tmp) ;
int OverlayWaitCallBack(void *Tmp) ;
