int  PlayListsplbutton1callback(int butno,int i,void *Tmp) ;
void  PlayListsplbutton1init(DIL *B,void *pt) ;
int  PlayListbrowser1callback(int item,int i,void *Tmp) ;
void  PlayListbrowser1init(DIX *X,void *pt) ;
int  PlayListbrowser2callback(int item,int i,void *Tmp) ;
void  PlayListbrowser2init(DIX *X,void *pt) ;
int  PlayListbutton1callback(int butno,int i,void *Tmp) ;
void  PlayListbutton1init(DIN *B,void *pt) ;
int PlayListinit(void *Tmp) ;
int PlayListcleanup(void *Tmp) ;
int PlayListCallBack(void *Tmp,void *tmp) ;
int PlayListResizeCallBack(void *Tmp) ;
int PlayListWaitCallBack(void *Tmp) ;
