int  ReorderImagessplbutton1callback(int butno,int i,void *Tmp) ;
void  ReorderImagessplbutton1init(DIL *B,void *pt) ;
int  ReorderImagesbrowser1callback(int item,int i,void *Tmp) ;
void  ReorderImagesbrowser1init(DIY *Y,void *pt) ;
int ReorderImagesinit(void *Tmp) ;
int ReorderImagescleanup(void *Tmp) ;
int ModifyReorderImages(void *Tmp,int GrpId) ;
int ReorderImagesCallBack(void *Tmp,void *tmp) ;
int ReorderImagesResizeCallBack(void *Tmp) ;
int ReorderImagesWaitCallBack(void *Tmp) ;
