int Rotate90RV90inputcallback(int cellno,int i,void *Tmp) ;
int Rotate90RV90inputbrowsecallback(int butno,int i,void *Tmp) ;
void  Rotate90RV90inputbrowseinit (DIN *B,void *pt) ;
int Rotate90RV90gocallback(int butno,int i,void *Tmp) ;
void  Rotate90RV90goinit (DIL *B,void *pt) ;
int Rotate90RV90outcallback(int cellno,int i,void *Tmp) ;
int Rotate90RV90Outbrowsecallback(int butno,int i,void *Tmp) ;
void  Rotate90RV90Outbrowseinit (DIN *B,void *pt) ;
int Rotate90RV90anglecallback(int item,int i,void *Tmp) ;
void  Rotate90RV90angleinit (DIRA *R,void *pt) ;
int Rotate90init(void *Tmp) ;
int Rotate90cleanup(void *Tmp) ;
void *RunRotate90(void *,void *) ;
int MakeRotate90Group(DIALOG *,void *) ;
void * Rotate90Action(void *,void *) ;
int ModifyRotate90(void *Tmp,int GrpId) ;
int Rotate90CallBack(void *Tmp,void *tmp) ;
int Rotate90ResizeCallBack(void *Tmp) ;
int Rotate90WaitCallBack(void *Tmp) ;
