int SidebySideSBSinput1callback(int cellno,int i,void *Tmp) ;
int SidebySideSBSinput1browsecallback(int butno,int i,void *Tmp) ;
void  SidebySideSBSinput1browseinit (DIN *B,void *pt) ;
int SidebySideSBSinput2callback(int cellno,int i,void *Tmp) ;
int SidebySideSBSinput2browsecallback(int butno,int i,void *Tmp) ;
void  SidebySideSBSinput2browseinit (DIN *B,void *pt) ;
int SidebySideSBSgocallback(int butno,int i,void *Tmp) ;
void  SidebySideSBSgoinit (DIL *B,void *pt) ;
int SidebySideSBSoutcallback(int cellno,int i,void *Tmp) ;
int SidebySideSBSOutbrowsecallback(int butno,int i,void *Tmp) ;
void  SidebySideSBSOutbrowseinit (DIN *B,void *pt) ;
int SidebySideinit(void *Tmp) ;
int SidebySidecleanup(void *Tmp) ;
void *RunSidebySide(void *,void *) ;
int MakeSidebySideGroup(DIALOG *,void *) ;
void * SidebySideAction(void *,void *) ;
int ModifySidebySide(void *Tmp,int GrpId) ;
int SidebySideCallBack(void *Tmp,void *tmp) ;
int SidebySideResizeCallBack(void *Tmp) ;
int SidebySideWaitCallBack(void *Tmp) ;
