int sliceSLCinputcallback(int cellno,int i,void *Tmp) ;
int sliceSLCinputbrowsecallback(int butno,int i,void *Tmp) ;
void  sliceSLCinputbrowseinit (DIN *B,void *pt) ;
int sliceSLCgocallback(int butno,int i,void *Tmp) ;
void  sliceSLCgoinit (DIL *B,void *pt) ;
int sliceSLCoutcallback(int cellno,int i,void *Tmp) ;
int sliceSLCOutbrowsecallback(int butno,int i,void *Tmp) ;
void  sliceSLCOutbrowseinit (DIN *B,void *pt) ;
int sliceSLCseccallback(int cellno,int i,void *Tmp) ;
int sliceinit(void *Tmp) ;
int slicecleanup(void *Tmp) ;
void *Runslice(void *,void *) ;
int MakesliceGroup(DIALOG *,void *) ;
void * sliceAction(void *,void *) ;
int sliceSetup(void *Tmp,void *args) ;
int Modifyslice(void *Tmp,int GrpId) ;
int sliceCallBack(void *Tmp,void *tmp) ;
int sliceResizeCallBack(void *Tmp) ;
int sliceWaitCallBack(void *Tmp) ;
