int textovervideoTOVinput1callback(int cellno,int i,void *Tmp) ;
int textovervideoTOVinput1browsecallback(int butno,int i,void *Tmp) ;
void  textovervideoTOVinput1browseinit (DIN *B,void *pt) ;
int textovervideoTOVinput2callback(int cellno,int i,void *Tmp) ;
int textovervideoTOVinput2browsecallback(int butno,int i,void *Tmp) ;
void  textovervideoTOVinput2browseinit (DIN *B,void *pt) ;
int textovervideoTOVgocallback(int butno,int i,void *Tmp) ;
void  textovervideoTOVgoinit (DIL *B,void *pt) ;
int textovervideoTOVoutcallback(int cellno,int i,void *Tmp) ;
int textovervideoTOVOutbrowsecallback(int butno,int i,void *Tmp) ;
void  textovervideoTOVOutbrowseinit (DIN *B,void *pt) ;
int textovervideoTOVtrescallback(int cellno,int i,void *Tmp) ;
int textovervideoTOVradiocallback(int item,int i,void *Tmp) ;
void  textovervideoTOVradioinit (DIRA *R,void *pt) ;
int textovervideoTOVbclrcallback(int butno,int i,void *Tmp) ;
void  textovervideoTOVbclrinit (DIN *B,void *pt) ;
int textovervideoTOVrfactcallback(int item,int i,void *Tmp) ;
int textovervideoTOVposcallback(int item,int i,void *Tmp) ;
int textovervideoinit(void *Tmp) ;
int textovervideocleanup(void *Tmp) ;
void *Runtextovervideo(void *,void *) ;
int MaketextovervideoGroup(DIALOG *,void *) ;
void * textovervideoAction(void *,void *) ;
int textovervideoSetup(void *Tmp,void *args) ;
int Modifytextovervideo(void *Tmp,int GrpId) ;
int textovervideoCallBack(void *Tmp,void *tmp) ;
int textovervideoResizeCallBack(void *Tmp) ;
int textovervideoWaitCallBack(void *Tmp) ;
