int  ToolBoxbrowser1callback(int item,int i,void *Tmp) ;
void  ToolBoxbrowser1init(DIX *X,void *pt) ;
int  ToolBoxsplbutton1callback(int butno,int i,void *Tmp) ;
void  ToolBoxsplbutton1init(DIL *B,void *pt) ;
int ToolBoxinit(void *Tmp) ;
int ToolBoxcleanup(void *Tmp) ;
int ModifyToolBox(void *Tmp,int GrpId) ;
int ToolBoxCallBack(void *Tmp,void *tmp) ;
int ToolBoxResizeCallBack(void *Tmp) ;
int ToolBoxWaitCallBack(void *Tmp) ;
