int topandbottomTABinput1callback(int cellno,int i,void *Tmp) ;
int topandbottomTABinput1browsecallback(int butno,int i,void *Tmp) ;
void  topandbottomTABinput1browseinit (DIN *B,void *pt) ;
int topandbottomTABinput2callback(int cellno,int i,void *Tmp) ;
int topandbottomTABinput2browsecallback(int butno,int i,void *Tmp) ;
void  topandbottomTABinput2browseinit (DIN *B,void *pt) ;
int topandbottomTABgocallback(int butno,int i,void *Tmp) ;
void  topandbottomTABgoinit (DIL *B,void *pt) ;
int topandbottomTABoutcallback(int cellno,int i,void *Tmp) ;
int topandbottomTABOutbrowsecallback(int butno,int i,void *Tmp) ;
void  topandbottomTABOutbrowseinit (DIN *B,void *pt) ;
int topandbottominit(void *Tmp) ;
int topandbottomcleanup(void *Tmp) ;
void *Runtopandbottom(void *,void *) ;
int MaketopandbottomGroup(DIALOG *,void *) ;
void * topandbottomAction(void *,void *) ;
int Modifytopandbottom(void *Tmp,int GrpId) ;
int topandbottomCallBack(void *Tmp,void *tmp) ;
int topandbottomResizeCallBack(void *Tmp) ;
int topandbottomWaitCallBack(void *Tmp) ;
