int  vfliptextbox1callback(int cellno,int i,void *Tmp);
int  vfliptextbox2callback(int cellno,int i,void *Tmp);
int  vflipbutton1callback(int butno,int i,void *Tmp) ;
void  vflipbutton1init(DIN *B,void *pt) ;
int  vflipsplbutton1callback(int butno,int i,void *Tmp) ;
void  vflipsplbutton1init(DIL *B,void *pt) ;
int vflipinit(void *Tmp) ;
int vflipcleanup(void *Tmp) ;
int vflipCallBack(void *Tmp,void *tmp) ;
int vflipResizeCallBack(void *Tmp) ;
int vflipWaitCallBack(void *Tmp) ;
