int VideoReverseVREVinputcallback(int cellno,int i,void *Tmp) ;
int VideoReverseVREVIbrowsecallback(int butno,int i,void *Tmp) ;
void  VideoReverseVREVIbrowseinit (DIN *B,void *pt) ;
int VideoReverseVREVoutputcallback(int cellno,int i,void *Tmp) ;
int VideoReverseVREVdocallback(int butno,int i,void *Tmp) ;
void  VideoReverseVREVdoinit (DIL *B,void *pt) ;
int VideoReverseVREVObrowsecallback(int butno,int i,void *Tmp) ;
void  VideoReverseVREVObrowseinit (DIN *B,void *pt) ;
int VideoReverseVREVradiocallback(int item,int i,void *Tmp) ;
void  VideoReverseVREVradioinit (DIRA *R,void *pt) ;
int VideoReverseinit(void *Tmp) ;
int VideoReversecleanup(void *Tmp) ;
void *RunVideoReverse(void *,void *) ;
int MakeVideoReverseGroup(DIALOG *,void *) ;
void * VideoReverseAction(void *,void *) ;
int VideoReverseSetup(void *Tmp,void *args) ;
int ModifyVideoReverse(void *Tmp,int GrpId) ;
int VideoReverseCallBack(void *Tmp,void *tmp) ;
int VideoReverseResizeCallBack(void *Tmp) ;
int VideoReverseWaitCallBack(void *Tmp) ;
