int  VideoJoinbrowser1callback(int item,int i,void *Tmp) ;
void  VideoJoinbrowser1init(DIX *X,void *pt) ;
int  VideoJoinbutton1callback(int butno,int i,void *Tmp) ;
void  VideoJoinbutton1init(DIN *B,void *pt) ;
int  VideoJointextbox1callback(int cellno,int i,void *Tmp);
int  VideoJoinsplbutton1callback(int butno,int i,void *Tmp) ;
void  VideoJoinsplbutton1init(DIL *B,void *pt) ;
int  VideoJoinbrowser2callback(int item,int i,void *Tmp) ;
void  VideoJoinbrowser2init(DIRA *R,void *pt) ;
int VideoJoininit(void *Tmp) ;
int VideoJoincleanup(void *Tmp) ;
int VideoJoinCallBack(void *Tmp,void *tmp) ;
int VideoJoinResizeCallBack(void *Tmp) ;
int VideoJoinWaitCallBack(void *Tmp) ;
