int VideoSpeedVSinputcallback(int cellno,int i,void *Tmp) ;
int VideoSpeedVSIbrowsecallback(int butno,int i,void *Tmp) ;
void  VideoSpeedVSIbrowseinit (DIN *B,void *pt) ;
int VideoSpeedVSoutputcallback(int cellno,int i,void *Tmp) ;
int VideoSpeedVSspeedcallback(int cellno,int i,void *Tmp) ;
int VideoSpeedVSdocallback(int butno,int i,void *Tmp) ;
void  VideoSpeedVSdoinit (DIL *B,void *pt) ;
int VideoSpeedVSObrowsecallback(int butno,int i,void *Tmp) ;
void  VideoSpeedVSObrowseinit (DIN *B,void *pt) ;
int VideoSpeedinit(void *Tmp) ;
int VideoSpeedcleanup(void *Tmp) ;
void *RunVideoSpeed(void *,void *) ;
int MakeVideoSpeedGroup(DIALOG *,void *) ;
void * VideoSpeedAction(void *,void *) ;
int VideoSpeedSetup(void *Tmp,void *args) ;
int ModifyVideoSpeed(void *Tmp,int GrpId) ;
int VideoSpeedCallBack(void *Tmp,void *tmp) ;
int VideoSpeedResizeCallBack(void *Tmp) ;
int VideoSpeedWaitCallBack(void *Tmp) ;
