int VideoJoinVideoListcallback(int item,int i,void *Tmp) ;
int VideoJoinVJFcovercallback(int item,int i,void *Tmp);
void  VideoJoinVJFcoverinit (DIRA *R,void *ptmp);
int VideoJoinSetup(void *Tmp,void *args);
void  VideoJoinVideoListinit (DIX *X,void *pt) ;
int VideoJoinVideoJoinWidget2callback(int butno,int i,void *Tmp) ;
void  VideoJoinVideoJoinWidget2init (DIN *B,void *pt) ;
int VideoJoinVjoinOutcallback(int cellno,int i,void *Tmp) ;
int VideoJoinJoinVideoscallback(int butno,int i,void *Tmp) ;
void  VideoJoinJoinVideosinit (DIL *B,void *pt) ;
int VideoJoinVJQualitycallback(int item,int i,void *Tmp) ;
void  VideoJoinVJQualityinit (DIRA *R,void *pt) ;
int VideoJoinVJObrowsecallback(int butno,int i,void *Tmp) ;
void  VideoJoinVJObrowseinit (DIN *B,void *pt) ;
int VideoJoininit(void *Tmp) ;
int VideoJoincleanup(void *Tmp) ;
void *RunVideoJoin(void *,void *) ;
int MakeVideoJoinGroup(DIALOG *,void *) ;
void * VideoJoinAction(void *,void *) ;
int ModifyVideoJoin(void *Tmp,int GrpId) ;
int VideoJoinCallBack(void *Tmp,void *tmp) ;
int VideoJoinResizeCallBack(void *Tmp) ;
int VideoJoinWaitCallBack(void *Tmp) ;
