void uiInitGph() {
  int l;
  static entry=0;
  char flname[200],reviewfile[200];

  DIG *G;
  kgDC *dc;
  pthread_mutex_lock(&_Initlock);
  entry++;
  G = D->d[i].g;
  dc = (kgDC *) malloc(sizeof(kgDC));
  G->D= (void *)1;
  G->wc = (kgWC *) malloc(sizeof(kgWC));
  G->dc = dc;
  G->Obj_opn=0;
  ui_initialise(G);
  for(l=0;l<10;l++) dc->st_ptr[l]=0;
  G->B_min = 10400;
  G->BACK_UP=0;
  G->OPEN=1;
  G->Byte=0;
  G->R_Byte=0;
  G->R_max=0;
  G->D_ON=0;
  G->MAG=1;
  G->img=NULL;
  G->rzimg=NULL;
  G->pixels=NULL;
  kgViewport(G,0.,0.,1.0,1.0);
  kgUserFrame(G,0.,0.,(float)(G->x2-G->x1),(float)(G->y2-G->y1));
  strcpy(flname,kgMakeTmpDir());
  strcat(flname,"/gphs");
  l = strlen(flname);
  sprintf(flname+l,"_%5.5d.%3.3d",getpid(),entry);
  strcpy(dc->objdir,flname);
//  printf("%s\n",dc->objdir);
  mkdir(dc->objdir,0700);
  strcpy(dc->reviewfile,dc->objdir);
  strcat(dc->reviewfile,"/reviewdat");
  G->rbuf = open(dc->reviewfile,O_CREAT|O_BINARY|O_TRUNC|O_RDWR,0666);
  strcpy(dc->plotfile,dc->objdir);
  strcat(dc->plotfile,"/plotgph");
  strcpy(dc->cmdsfile,dc->objdir);
  strcat(dc->cmdsfile,"/cmdsfile");
  dc->ls_list=NULL;
  dc->No_of_lights=0;
  G->Rbuff = (unsigned char  *) malloc(B_max+100);
  G->hbuf =-1;
  uiinitialise(G);
  pthread_mutex_unlock(&_Initlock);
}
