int  FileListBrowserbutton1callback(int butno,int i,void *Tmp) ;
void  FileListBrowserbutton1init(DIN *B,void *pt) ;
int  FileListBrowsertextbox1callback(int cellno,int i,void *Tmp);
int  FileListBrowserbrowser1callback(int item,int i,void *Tmp) ;
void  FileListBrowserbrowser1init(DIX *X,void *pt) ;
int  FileListBrowserbrowser2callback(int item,int i,void *Tmp) ;
void  FileListBrowserbrowser2init(DIY *Y,void *pt) ;
int  FileListBrowserbrowser3callback(int item,int i,void *Tmp) ;
void  FileListBrowserbrowser3init(DIY *Y,void *pt) ;
int  FileListBrowserbutton2callback(int butno,int i,void *Tmp) ;
void  FileListBrowserbutton2init(DIN *B,void *pt) ;
int  FileListBrowsersplbutton1callback(int butno,int i,void *Tmp) ;
void  FileListBrowsersplbutton1init(DIL *B,void *pt) ;
int  FileListBrowserbutton3callback(int butno,int i,void *Tmp) ;
void  FileListBrowserbutton3init(DIN *B,void *pt) ;
int FileListBrowserinit(void *Tmp) ;
int FileListBrowsercleanup(void *Tmp) ;
int ModifyFileListBrowser(void *Tmp,int GrpId) ;
int FileListBrowserCallBack(void *Tmp,void *tmp) ;
int FileListBrowserResizeCallBack(void *Tmp) ;
int FileListBrowserWaitCallBack(void *Tmp) ;
