int  keybrdbutton1callback(int butno,int i,void *Tmp) ;
void  keybrdbutton1init(DIN *B,void *pt) ;
int  keybrdbutton2callback(int butno,int i,void *Tmp) ;
void  keybrdbutton2init(DIN *B,void *pt) ;
int  keybrdbutton3callback(int butno,int i,void *Tmp) ;
void  keybrdbutton3init(DIN *B,void *pt) ;
int  keybrdbutton4callback(int butno,int i,void *Tmp) ;
void  keybrdbutton4init(DIN *B,void *pt) ;
int  keybrdbutton5callback(int butno,int i,void *Tmp) ;
void  keybrdbutton5init(DIN *B,void *pt) ;
int  keybrdbutton6callback(int butno,int i,void *Tmp) ;
void  keybrdbutton6init(DIN *B,void *pt) ;
int  keybrdbutton7callback(int butno,int i,void *Tmp) ;
void  keybrdbutton7init(DIN *B,void *pt) ;
int  keybrdbutton8callback(int butno,int i,void *Tmp) ;
void  keybrdbutton8init(DIN *B,void *pt) ;
int  keybrdbutton9callback(int butno,int i,void *Tmp) ;
void  keybrdbutton9init(DIN *B,void *pt) ;
int  keybrdbutton10callback(int butno,int i,void *Tmp) ;
void  keybrdbutton10init(DIN *B,void *pt) ;
int  keybrdbutton11callback(int butno,int i,void *Tmp) ;
void  keybrdbutton11init(DIN *B,void *pt) ;
int  keybrdbutton12callback(int butno,int i,void *Tmp) ;
void  keybrdbutton12init(DIN *B,void *pt) ;
int  keybrdbutton13callback(int butno,int i,void *Tmp) ;
void  keybrdbutton13init(DIN *B,void *pt) ;
int  keybrdbutton14callback(int butno,int i,void *Tmp) ;
void  keybrdbutton14init(DIN *B,void *pt) ;
int  keybrdbutton15callback(int butno,int i,void *Tmp) ;
void  keybrdbutton15init(DIN *B,void *pt) ;
int  keybrdbutton16callback(int butno,int i,void *Tmp) ;
void  keybrdbutton16init(DIN *B,void *pt) ;
int  keybrdbutton17callback(int butno,int i,void *Tmp) ;
void  keybrdbutton17init(DIN *B,void *pt) ;
int  keybrdbutton18callback(int butno,int i,void *Tmp) ;
void  keybrdbutton18init(DIN *B,void *pt) ;
int  keybrdbutton19callback(int butno,int i,void *Tmp) ;
void  keybrdbutton19init(DIN *B,void *pt) ;
int keybrdinit(void *Tmp) ;
int keybrdcleanup(void *Tmp) ;
int keybrdCallBack(void *Tmp,void *tmp) ;
int keybrdResizeCallBack(void *Tmp) ;
int keybrdWaitCallBack(void *Tmp) ;
