int  keybrd4button1callback(int butno,int i,void *Tmp) ;
void  keybrd4button1init(DIN *B,void *pt) ;
int  keybrd4button2callback(int butno,int i,void *Tmp) ;
void  keybrd4button2init(DIN *B,void *pt) ;
int  keybrd4button3callback(int butno,int i,void *Tmp) ;
void  keybrd4button3init(DIN *B,void *pt) ;
int  keybrd4button4callback(int butno,int i,void *Tmp) ;
void  keybrd4button4init(DIN *B,void *pt) ;
int  keybrd4button5callback(int butno,int i,void *Tmp) ;
void  keybrd4button5init(DIN *B,void *pt) ;
int  keybrd4button6callback(int butno,int i,void *Tmp) ;
void  keybrd4button6init(DIN *B,void *pt) ;
int  keybrd4button7callback(int butno,int i,void *Tmp) ;
void  keybrd4button7init(DIN *B,void *pt) ;
int  keybrd4button8callback(int butno,int i,void *Tmp) ;
void  keybrd4button8init(DIN *B,void *pt) ;
int  keybrd4button9callback(int butno,int i,void *Tmp) ;
void  keybrd4button9init(DIN *B,void *pt) ;
int  keybrd4button10callback(int butno,int i,void *Tmp) ;
void  keybrd4button10init(DIN *B,void *pt) ;
int  keybrd4button11callback(int butno,int i,void *Tmp) ;
void  keybrd4button11init(DIN *B,void *pt) ;
int  keybrd4button12callback(int butno,int i,void *Tmp) ;
void  keybrd4button12init(DIN *B,void *pt) ;
int  keybrd4button13callback(int butno,int i,void *Tmp) ;
void  keybrd4button13init(DIN *B,void *pt) ;
int  keybrd4button14callback(int butno,int i,void *Tmp) ;
void  keybrd4button14init(DIN *B,void *pt) ;
int  keybrd4button15callback(int butno,int i,void *Tmp) ;
void  keybrd4button15init(DIN *B,void *pt) ;
int  keybrd4button16callback(int butno,int i,void *Tmp) ;
void  keybrd4button16init(DIN *B,void *pt) ;
int  keybrd4button17callback(int butno,int i,void *Tmp) ;
void  keybrd4button17init(DIN *B,void *pt) ;
int  keybrd4button18callback(int butno,int i,void *Tmp) ;
void  keybrd4button18init(DIN *B,void *pt) ;
int  keybrd4button19callback(int butno,int i,void *Tmp) ;
void  keybrd4button19init(DIN *B,void *pt) ;
int  keybrd4button20callback(int butno,int i,void *Tmp) ;
void  keybrd4button20init(DIN *B,void *pt) ;
int  keybrd4button21callback(int butno,int i,void *Tmp) ;
void  keybrd4button21init(DIN *B,void *pt) ;
int  keybrd4button22callback(int butno,int i,void *Tmp) ;
void  keybrd4button22init(DIN *B,void *pt) ;
int keybrd4init(void *Tmp) ;
int keybrd4cleanup(void *Tmp) ;
int Modifykeybrd4(void *Tmp,int GrpId) ;
int keybrd4CallBack(void *Tmp,void *tmp) ;
int keybrd4ResizeCallBack(void *Tmp) ;
int keybrd4WaitCallBack(void *Tmp) ;
