int  keybrd0button1callback(int butno,int i,void *Tmp) ;
void  keybrd0button1init(DIN *B,void *pt) ;
int  keybrd0button2callback(int butno,int i,void *Tmp) ;
void  keybrd0button2init(DIN *B,void *pt) ;
int  keybrd0button3callback(int butno,int i,void *Tmp) ;
void  keybrd0button3init(DIN *B,void *pt) ;
int  keybrd0button4callback(int butno,int i,void *Tmp) ;
void  keybrd0button4init(DIN *B,void *pt) ;
int  keybrd0button5callback(int butno,int i,void *Tmp) ;
void  keybrd0button5init(DIN *B,void *pt) ;
int  keybrd0button6callback(int butno,int i,void *Tmp) ;
void  keybrd0button6init(DIN *B,void *pt) ;
int  keybrd0button7callback(int butno,int i,void *Tmp) ;
void  keybrd0button7init(DIN *B,void *pt) ;
int  keybrd0button8callback(int butno,int i,void *Tmp) ;
void  keybrd0button8init(DIN *B,void *pt) ;
int  keybrd0button9callback(int butno,int i,void *Tmp) ;
void  keybrd0button9init(DIN *B,void *pt) ;
int  keybrd0button10callback(int butno,int i,void *Tmp) ;
void  keybrd0button10init(DIN *B,void *pt) ;
int  keybrd0button11callback(int butno,int i,void *Tmp) ;
void  keybrd0button11init(DIN *B,void *pt) ;
int  keybrd0button12callback(int butno,int i,void *Tmp) ;
void  keybrd0button12init(DIN *B,void *pt) ;
int  keybrd0button13callback(int butno,int i,void *Tmp) ;
void  keybrd0button13init(DIN *B,void *pt) ;
int  keybrd0button14callback(int butno,int i,void *Tmp) ;
void  keybrd0button14init(DIN *B,void *pt) ;
int  keybrd0button15callback(int butno,int i,void *Tmp) ;
void  keybrd0button15init(DIN *B,void *pt) ;
int  keybrd0button16callback(int butno,int i,void *Tmp) ;
void  keybrd0button16init(DIN *B,void *pt) ;
int  keybrd0button17callback(int butno,int i,void *Tmp) ;
void  keybrd0button17init(DIN *B,void *pt) ;
int  keybrd0button18callback(int butno,int i,void *Tmp) ;
void  keybrd0button18init(DIN *B,void *pt) ;
int  keybrd0button19callback(int butno,int i,void *Tmp) ;
void  keybrd0button19init(DIN *B,void *pt) ;
int  keybrd0button20callback(int butno,int i,void *Tmp) ;
void  keybrd0button20init(DIN *B,void *pt) ;
int  keybrd0button21callback(int butno,int i,void *Tmp) ;
void  keybrd0button21init(DIN *B,void *pt) ;
int keybrd0init(void *Tmp) ;
int keybrd0cleanup(void *Tmp) ;
int keybrd0CallBack(void *Tmp,void *tmp) ;
int keybrd0ResizeCallBack(void *Tmp) ;
int keybrd0WaitCallBack(void *Tmp) ;
