int  keybrd5button1callback(int butno,int i,void *Tmp) ;
void  keybrd5button1init(DIN *B,void *pt) ;
int  keybrd5button2callback(int butno,int i,void *Tmp) ;
void  keybrd5button2init(DIN *B,void *pt) ;
int  keybrd5button3callback(int butno,int i,void *Tmp) ;
void  keybrd5button3init(DIN *B,void *pt) ;
int  keybrd5button4callback(int butno,int i,void *Tmp) ;
void  keybrd5button4init(DIN *B,void *pt) ;
int  keybrd5button5callback(int butno,int i,void *Tmp) ;
void  keybrd5button5init(DIN *B,void *pt) ;
int  keybrd5button6callback(int butno,int i,void *Tmp) ;
void  keybrd5button6init(DIN *B,void *pt) ;
int  keybrd5button7callback(int butno,int i,void *Tmp) ;
void  keybrd5button7init(DIN *B,void *pt) ;
int  keybrd5button8callback(int butno,int i,void *Tmp) ;
void  keybrd5button8init(DIN *B,void *pt) ;
int  keybrd5button9callback(int butno,int i,void *Tmp) ;
void  keybrd5button9init(DIN *B,void *pt) ;
int  keybrd5button10callback(int butno,int i,void *Tmp) ;
void  keybrd5button10init(DIN *B,void *pt) ;
int  keybrd5button11callback(int butno,int i,void *Tmp) ;
void  keybrd5button11init(DIN *B,void *pt) ;
int  keybrd5button12callback(int butno,int i,void *Tmp) ;
void  keybrd5button12init(DIN *B,void *pt) ;
int  keybrd5button13callback(int butno,int i,void *Tmp) ;
void  keybrd5button13init(DIN *B,void *pt) ;
int  keybrd5button14callback(int butno,int i,void *Tmp) ;
void  keybrd5button14init(DIN *B,void *pt) ;
int  keybrd5button15callback(int butno,int i,void *Tmp) ;
void  keybrd5button15init(DIN *B,void *pt) ;
int  keybrd5button16callback(int butno,int i,void *Tmp) ;
void  keybrd5button16init(DIN *B,void *pt) ;
int  keybrd5button17callback(int butno,int i,void *Tmp) ;
void  keybrd5button17init(DIN *B,void *pt) ;
int  keybrd5button18callback(int butno,int i,void *Tmp) ;
void  keybrd5button18init(DIN *B,void *pt) ;
int  keybrd5button19callback(int butno,int i,void *Tmp) ;
void  keybrd5button19init(DIN *B,void *pt) ;
int  keybrd5button20callback(int butno,int i,void *Tmp) ;
void  keybrd5button20init(DIN *B,void *pt) ;
int  keybrd5button21callback(int butno,int i,void *Tmp) ;
void  keybrd5button21init(DIN *B,void *pt) ;
int  keybrd5button22callback(int butno,int i,void *Tmp) ;
void  keybrd5button22init(DIN *B,void *pt) ;
int  keybrd5button23callback(int butno,int i,void *Tmp) ;
void  keybrd5button23init(DIN *B,void *pt) ;
int  keybrd5button24callback(int butno,int i,void *Tmp) ;
void  keybrd5button24init(DIN *B,void *pt) ;
int  keybrd5button25callback(int butno,int i,void *Tmp) ;
void  keybrd5button25init(DIN *B,void *pt) ;
int  keybrd5button26callback(int butno,int i,void *Tmp) ;
void  keybrd5button26init(DIN *B,void *pt) ;
int keybrd5init(void *Tmp) ;
int keybrd5cleanup(void *Tmp) ;
int Modifykeybrd5(void *Tmp,int GrpId) ;
int Modifykeybrd5(void *Tmp,int GrpId) ;
int keybrd5CallBack(void *Tmp,void *tmp) ;
int keybrd5ResizeCallBack(void *Tmp) ;
int keybrd5WaitCallBack(void *Tmp) ;
