#define EndKey       1
#define InsertKey    2
#define DeleteKey    3
#define ClearKey     4
#define BackspaceKey 5
#define PageupKey    6
#define PagedownKey  7
#define LeftKey      8
#define RightKey     9
#define DownKey      10
#define UpKey        11
#define CapslockKey   12
#define ShiftKey     13
#define CntlKey      14
#define AltKey       15
#define LinefeedKey  16
#define ReturnKey    17
#define EscapeKey    18
#define HomeKey      19
#define TabKey       20
#define SpaceKey     21
#define PrintKey     22
#define ShiftRightKey 23
#define ShiftLockKey  24
