int  skeybrdbutton1callback(int butno,int i,void *Tmp) ;
void  skeybrdbutton1init(DIN *B,void *pt) ;
int  skeybrdbutton2callback(int butno,int i,void *Tmp) ;
void  skeybrdbutton2init(DIN *B,void *pt) ;
int  skeybrdbutton3callback(int butno,int i,void *Tmp) ;
void  skeybrdbutton3init(DIN *B,void *pt) ;
int  skeybrdbutton4callback(int butno,int i,void *Tmp) ;
void  skeybrdbutton4init(DIN *B,void *pt) ;
int  skeybrdbutton5callback(int butno,int i,void *Tmp) ;
void  skeybrdbutton5init(DIN *B,void *pt) ;
int  skeybrdbutton6callback(int butno,int i,void *Tmp) ;
void  skeybrdbutton6init(DIN *B,void *pt) ;
int  skeybrdbutton7callback(int butno,int i,void *Tmp) ;
void  skeybrdbutton7init(DIN *B,void *pt) ;
int skeybrdinit(void *Tmp) ;
int skeybrdcleanup(void *Tmp) ;
int skeybrdCallBack(void *Tmp,void *tmp) ;
int skeybrdResizeCallBack(void *Tmp) ;
int skeybrdWaitCallBack(void *Tmp) ;
