/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DESKTOPFILEDIR "/home/kulina/BUILD/kgmplayer/share/applications"

#define DISABLE_LIBTOOL_PRELOAD 1

#define DISABLE_ORC 1

#define ENABLE_LEGACY_DATABASE_ENTRY_FORMAT 1

#define ENABLE_NLS 1

#define GETGROUPS_T gid_t

#define GETTEXT_PACKAGE "pulseaudio"

#define HAVE_ACCEPT4 1

#define HAVE_ALSA 1

#define HAVE_ALSA_UCM 1

#define HAVE_ARPA_INET_H 1

#define HAVE_ATOMIC_BUILTINS 1

#define HAVE_ATOMIC_BUILTINS_MEMORY_MODEL 1

#define HAVE_AVAHI 0

#define HAVE_BYTESWAP_H 1

#define HAVE_CLOCK_GETTIME 1

#define HAVE_COREAUDIO 0

#define HAVE_CPUID_H 1

#define HAVE_CTIME_R 1

#define HAVE_DECL_ENVIRON 1

#define HAVE_DECL_SOUND_PCM_READ_BITS 1

#define HAVE_DECL_SOUND_PCM_READ_CHANNELS 1

#define HAVE_DECL_SOUND_PCM_READ_RATE 1

#define HAVE_DLADDR 1

#define HAVE_DLFCN_H 1

#define HAVE_EXECINFO_H 1

#define HAVE_FAST_64BIT_OPERATIONS 1

#define HAVE_FCHMOD 1

#define HAVE_FCHOWN 1

#define HAVE_FORK 1

#define HAVE_FSTAT 1

#define HAVE_GETADDRINFO 1

#define HAVE_GETGRGID_R 1

#define HAVE_GETGRNAM_R 1

#define HAVE_GETPWNAM_R 1

#define HAVE_GETPWUID_R 1

#define HAVE_GETTIMEOFDAY 1

#define HAVE_GETUID 1

#define HAVE_GRP_H 1

#define HAVE_GSETTINGS 0

#define HAVE_HAL_COMPAT 1

#define HAVE_ICONV 1

#define HAVE_IPV6 1

#define HAVE_LANGINFO_H 1

#define HAVE_LINUX_SOCKIOS_H 1

#define HAVE_LOCALE_H 1

#define HAVE_LRINTF 1

#define HAVE_LSTAT 1

#define HAVE_MEMFD 1

#define HAVE_MEMFD_CREATE 1

#define HAVE_MKFIFO 1

#define HAVE_MLOCK 1

/* Compiler supports mmx. */
#define HAVE_MMX 1

#define HAVE_NANOSLEEP 1

#define HAVE_NETDB_H 1

#define HAVE_NETINET_IN_H 1

#define HAVE_NETINET_IN_SYSTM_H 1

#define HAVE_NETINET_IP_H 1

#define HAVE_NETINET_TCP_H 1

#define HAVE_OPEN64 1

#define HAVE_OSS_OUTPUT 1

#define HAVE_OSS_WRAPPER 1

#define HAVE_PCREPOSIX_H 1

#define HAVE_PIPE 1

#define HAVE_PIPE2 1

#define HAVE_POLL_H 1

#define HAVE_POSIX_FADVISE 1

#define HAVE_POSIX_MADVISE 1

#define HAVE_POSIX_MEMALIGN 1

#define HAVE_PPOLL 1

#define HAVE_PTHREAD 1

#define HAVE_PTHREAD_GETNAME_NP 1

#define HAVE_PTHREAD_PRIO_INHERIT 1

#define HAVE_PTHREAD_SETAFFINITY_NP 1

#define HAVE_PTHREAD_SETNAME_NP 1

#define HAVE_PWD_H 1

#define HAVE_READLINK 1

#define HAVE_REGEX_H 1

#define HAVE_RUNNING_FROM_BUILD_TREE 1

#define HAVE_SCHED_H 1

#define HAVE_SETEGID 1

#define HAVE_SETEUID 1

#define HAVE_SETPGID 1

#define HAVE_SETREGID 1

#define HAVE_SETRESGID 1

#define HAVE_SETRESUID 1

#define HAVE_SETREUID 1

#define HAVE_SETSID 1

#define HAVE_SHM_OPEN 1

#define HAVE_SIGACTION 1

#define HAVE_SIGXCPU 1

/* Compiler supports sse. */
#define HAVE_SSE 1

#define HAVE_STDINT_H 1

#define HAVE_STD_BOOL 1

#define HAVE_STRERROR_R 1

#define HAVE_STRTOD_L 1

#define HAVE_STRTOF 1

#define HAVE_SYMLINK 1

#define HAVE_SYSCONF 1

#define HAVE_SYSLOG_H 1

#define HAVE_SYSTEMD_LOGIN 1

#define HAVE_SYS_CAPABILITY_H 1

#define HAVE_SYS_EVENTFD_H 1

#define HAVE_SYS_IOCTL_H 1

#define HAVE_SYS_MMAN_H 1

#define HAVE_SYS_PRCTL_H 1

#define HAVE_SYS_RESOURCE_H 1

#define HAVE_SYS_SELECT_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_SYSCALL_H 1

#define HAVE_SYS_UIO_H 1

#define HAVE_SYS_UN_H 1

#define HAVE_SYS_WAIT_H 1

#define HAVE_UDEV 1

#define HAVE_UNAME 1

#define HAVE_WAVEOUT 0

#define ICONV_CONST 

#define LIBICONV_PLUG 1

#define MESON_BUILD 1

#define OS_IS_FREEBSD 0

#define PACKAGE "pulseaudio"

#define PACKAGE_NAME "pulseaudio"

#define PACKAGE_VERSION "16.1"

#define PA_ACCESS_GROUP "pulse-access"

#define PA_ALSA_PATHS_DIR "/home/kulina/BUILD/kgmplayer/share/pulseaudio/alsa-mixer/paths"

#define PA_ALSA_PROFILE_SETS_DIR "/home/kulina/BUILD/kgmplayer/share/pulseaudio/alsa-mixer/profile-sets"

#define PA_API_VERSION 12

#define PA_BINARY "/home/kulina/BUILD/kgmplayer/bin/pulseaudio"

#define PA_BUILDDIR "/home/kulina/BUILD/kgmplayer/OpenSource"

#define PA_CFLAGS "Not yet supported on meson"

#define PA_DEFAULT_CONFIG_DIR "/home/kulina/BUILD/kgmplayer/etc/pulse"

#define PA_DEFAULT_CONFIG_DIR_UNQUOTED /home/kulina/BUILD/kgmplayer/etc/pulse

#define PA_DLSEARCHPATH "/home/kulina/BUILD/kgmplayer/lib64/pulseaudio/modules"

#define PA_INCDIR /home/kulina/BUILD/kgmplayer/include

#define PA_LIBDIR /home/kulina/BUILD/kgmplayer/lib64

#define PA_MACHINE_ID "/home/kulina/BUILD/kgmplayer/etc/machine-id"

#define PA_MACHINE_ID_FALLBACK "/home/kulina/BUILD/kgmplayer/var/lib/dbus/machine-id"

#define PA_MAJOR 16

#define PA_MINOR 1

#define PA_PROTOCOL_VERSION 35

#define PA_SOEXT ".so"

#define PA_SRCDIR "/home/kulina/BUILD/kgmplayer/OpenSource/pulseaudio-16.1/src"

#define PA_SYSTEM_CONFIG_PATH "/home/kulina/BUILD/kgmplayer/var/lib/pulse"

#define PA_SYSTEM_GROUP "pulse"

#define PA_SYSTEM_RUNTIME_PATH "/home/kulina/BUILD/kgmplayer/var/run/pulse"

#define PA_SYSTEM_STATE_PATH "/home/kulina/BUILD/kgmplayer/var/lib/pulse"

#define PA_SYSTEM_USER "pulse"

#define PULSEDSP_LOCATION /home/kulina/BUILD/kgmplayer/lib64/pulseaudio

#define PULSE_LOCALEDIR "/home/kulina/BUILD/kgmplayer/share/locale"

#define USE_SMOOTHER_2 1

#define top_srcdir /home/kulina/BUILD/kgmplayer/OpenSource/pulseaudio-16.1

