#! /bin/bash 
PREFIX=/home/kulina/BUILD/kgmplayer
KULINA=/home/kulina/BUILD/kgmplayer
export CFLAGS="-fPIC -fpic -I/home/kulina/BUILD/kgmplayer/include"
export LDFLAGS="-L/home/kulina/BUILD/kgmplayer/lib "
export X11_CFLAGS="-I/home/kulina/BUILD/kgmplayer/include "
export X11_LIBS="-lX11 "
export PKG_CONFIG_PATH=/home/kulina/BUILD/kgmplayer/lib/pkgconfig:/usr/X11R76/lib/pkgconfig:/home/kulina/BUILD/kgmplayer/lib/pkgconfig:/usr/X11R76/lib/pkgconfig
export LD_LIBRARY_PATH=/home/kulina/BUILD/kgmplayer/lib:/usr/X11R76/lib:
export PATH=/home/kulina/BUILD/kgmplayer/bin:/opt/rustc/bin:/bin:/opt/qt5/bin:/usr/bin
#export PKG_CONFIG_PATH=$KULINA/lib/pkgconfig
export LD_CONFIG_PATH=$LD_CONFIG_PATH:$KULINA/lib
export LDFLAGS=-L$KULINA/lib
echo $LDFLAGS
export CPPFLAGS="-fpic -fPIC -I$KULINA/include"
export ZLIBLIB=$KULINA/lib
export ZLIBINC=$KULINA/include
echo $CFLAGS
echo $PKG_CONFIG_PATH
echo "$X11_LIBS"
echo "$X11_CFLAGS"
tar xf json-c.tar.xz
cd json-c
rm -rf build
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$KULINA ..
make -j1
make install
cd ../..
rm -rf json-c
tar xf libsndfile-1.0.25.tar.gz
cd libsndfile-1.0.25
./configure --prefix=$KULINA --enable-static --disable-shared
make -j1
make install
cd ..
rm -rf libsndfile-1.0.25
tar xf intltool-0.51.0.tar.gz
cd intltool-0.51.0
./configure --prefix=$KULINA 
make
make install
cd ..
rm -rf intltool-0.51.0
tar xf libtool-2.4.7.tar.xz
cd libtool-2.4.7
./configure --prefix=$KULINA --enable-ltdl-install --enable-shared=yes --enable-shared=yes
make
make install
cd ..
rm -rf libtool-2.4.7
rm -rf alsa-lib-1.2.8
tar xf alsa-lib-1.2.8.tar.bz2
cd alsa-lib-1.2.8
./configure --prefix=$KULINA --enable-static=yes --disable-shared
make
make install
cd ..
rm alsa-lib-1.2.8
tar xf pulseaudio-16.1.tar.xz
cd pulseaudio-16.1
rm -rf build
mkdir build
cd build
meson --prefix=$KULINA       \
      --buildtype=release \
      -Ddatabase=gdbm     \
      -Ddoxygen=false     \
      -Dbluez5=disabled   &&
ninja
ninja install
cd ../..
#rm -rf pulseaudio-16.1
