#! /bin/bash 
PREFIX=/home/kulina/BUILD/kgmplayer
KULINA=/home/kulina/BUILD/kgmplayer
export CFLAGS="-I/home/kulina/BUILD/kgmplayer/include"
export LDFLAGS="-L/home/kulina/BUILD/kgmplayer/lib "
export X11_CFLAGS="-I/home/kulina/BUILD/kgmplayer/include "
export X11_LIBS="-lX11 "
export PKG_CONFIG_PATH=/home/kulina/BUILD/kgmplayer/lib/pkgconfig:/usr/X11R76/lib/pkgconfig:/home/kulina/BUILD/kgmplayer/lib/pkgconfig:/usr/X11R76/lib/pkgconfig
export LD_LIBRARY_PATH=/home/kulina/BUILD/kgmplayer/lib:/usr/X11R76/lib:
export PATH=/home/kulina/BUILD/kgmplayer/bin:/opt/rustc/bin:/bin:/opt/qt5/bin:/usr/bin
#export PKG_CONFIG_PATH=$KULINA/lib/pkgconfig
export LD_CONFIG_PATH=$LD_CONFIG_PATH:$KULINA/lib
export LDFLAGS=-L$KULINA/lib
echo $LDFLAGS
export CFLAGS="-fPIC -fpic -I$KULINA/include"
export CPPFLAGS="-fPIC -fpic -I$KULINA/include"
export ZLIBLIB=$KULINA/lib
export ZLIBINC=$KULINA/include
echo $CFLAGS
echo $PKG_CONFIG_PATH
echo "$X11_LIBS"
echo "$X11_CFLAGS"
rm -rf libtool-2.4.7
tar xf libtool-2.4.7.tar.xz
cd libtool-2.4.7
./configure --prefix=$KULINA --enable-static --disable-shared
make
make install
#rm libtool-2.4.7
