#! /bin/bash 
PREFIX=/home/kulina/BUILD/kgmplayer
KULINA=/home/kulina/BUILD/kgmplayer
export CFLAGS="-fPIC  -I/home/kulina/BUILD/kgmplayer/include"
export LDFLAGS="-L/home/kulina/BUILD/kgmplayer/lib "
export X11_CFLAGS="-I/home/kulina/BUILD/kgmplayer/include "
export X11_LIBS="-lX11 "
export PKG_CONFIG_PATH=/home/kulina/BUILD/kgmplayer/lib/pkgconfig:/usr/X11R76/lib/pkgconfig:/home/kulina/BUILD/kgmplayer/lib/pkgconfig:/usr/X11R76/lib/pkgconfig
export LD_LIBRARY_PATH=/home/kulina/BUILD/kgmplayer/lib:/usr/X11R76/lib:
export PATH=/home/kulina/BUILD/kgmplayer/bin:/opt/rustc/bin:/bin:/opt/qt5/bin:/usr/bin
#export PKG_CONFIG_PATH=$KULINA/lib/pkgconfig
export LD_CONFIG_PATH=$LD_CONFIG_PATH:$KULINA/lib
export LDFLAGS=-L$KULINA/lib
echo $LDFLAGS
export CPPFLAGS="-fpic -fPIC -I$KULINA/include"
export ZLIBLIB=$KULINA/lib
export ZLIBINC=$KULINA/include
export CFLAGS="$CFLAGS -fPIC -I$KULINA/include"
echo $CFLAGS
$CFLAGS
echo $PKG_CONFIG_PATH
echo "$X11_LIBS"
echo "$X11_CFLAGS"
tar xf libsndfile-1.0.25.tar.gz
cd libsndfile-1.0.25
./configure --prefix=$KULINA  --enable-static --disable-shared
make -j1
make install
cd ..
tar xf pulseaudio-12.2.tar.xz
cd pulseaudio-12.2
./configure --prefix=$KULINA --enable-static --disable-openssl --disable-x11 --disable-glib2 --disable-dbus \
  --disable-oss --disable-rpath --disable-tests --disable-default-build-tests --without-caps\
  --disable-asyncns 
make -j4
make install
cp src/.libs/libpulse*.a $KULINA/lib/
cd ..
#rm -rf pulseaudio-12.2
